### ISSUE TITLE
Task list for VK_EXT_index_type_uint8 release

### ISSUE THREAD

**Issue by pdaniell-nv** [KhronosGroup/Vulkan-Docs#1013]
The Vulkan 1.1.117 spec release includes the [VK_EXT_index_type_uint8](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/chap44.html#VK_EXT_index_type_uint8) extension. This extension allows implementations to use uint8 index buffers for indexed draw.

The task list for the VK_EXT_index_type_uint8 extension release is:

* [x] Vulkan specification (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/chap44.html#VK_EXT_index_type_uint8)
* [x] Validation layer (https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/1174)
* [x] Conformance tests (https://github.com/KhronosGroup/VK-GL-CTS/releases/tag/vulkan-cts-1.1.5.1)

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.
