### ISSUE TITLE
Task list for VK_KHR_pipeline_executable_properties release 

### ISSUE THREAD

**Issue by jekstrand** [KhronosGroup/Vulkan-Docs#1019]
The Vulkan 1.1.119 spec release includes the [VK_KHR_pipeline_executable_poperties](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VK_KHR_pipeline_executable_properties) extension.  This extension adds a mechanism to query properties and statistics about the different executables produced by the pipeline compilation process.  This is intended to be used by debugging and performance tools to allow them to provide more detailed information to the user.

The task list for the VK_KHR_pipeline_executable_properties extension release is:

- [x] Vulkan specification (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VK_KHR_pipeline_executable_properties)
- [x] validation layer (KhronosGroup/Vulkan-ValidationLayers#1131)
- [x] Conformance tests (https://github.com/KhronosGroup/VK-GL-CTS/releases/tag/vulkan-cts-1.1.5.1)

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.

**Comment by pdaniell-nv** [comment]
An implementation of this extension for NVIDIA GPUs can be found here: https://developer.nvidia.com/vulkan-driver
