### ISSUE TITLE
Task list for VK_KHR_timeline_semaphore release

### ISSUE THREAD

**Issue by jekstrand** [KhronosGroup/Vulkan-Docs#1047]
The Vulkan 1.1.124 spec release includes the[ VK_KHR_timeline_semaphore](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VK_KHR_timeline_semaphore) extension. This extension introduces a new type of semaphore that has an integer payload identifying a point in a timeline. Such timeline semaphores support the following operations:

 - Host query - A host operation that allows querying the payload of the timeline semaphore.
 - Host wait - A host operation that allows a blocking wait for a timeline semaphore to reach a specified value.
 - Host signal - A host operation that allows advancing the timeline semaphore to a specified value.
 - Device wait - A device operation that allows waiting for a timeline semaphore to reach a specified value.
 - Device signal - A device operation that allows advancing the timeline semaphore to a specified value.

In order to provide the extension as broadly as possible, we are providing a liberally licensed layered implementation that provides an implementation of VK_KHR_timeline_semaphore on top of `VkFence` and `VkSemaphore` primitives from Vulkan 1.0.  The layer supports any Vulkan 1.0 driver and does not require any additional extensions.  The layer provides a full-featured implementation with the exception that it does not support sharing of timeline semaphores via VK_KHR_external_semaphore due to OS limitations.

> **NOTE:** The layer may also have slightly worse performance than a native implementation and may impose additional synchronization due to difficulties in managing binary semaphore lifetimes.  However, it is expected to perform well enough to be shipped with a production application.

The task list for the VK_KHR_timeline_semaphore extension release is:

- [x] Vulkan specification (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VK_KHR_timeline_semaphore)
- [x] Layered implementation (https://gitlab.freedesktop.org/mesa/vulkan-wsi-layer/merge_requests/4)
- [x] validation layer support (KhronosGroup/Vulkan-ValidationLayers#1394, KhronosGroup/Vulkan-ValidationLayers#1511, KhronosGroup/Vulkan-ValidationLayers#1622)
- [x] Conformance tests ([Vulkan CTS 1.1.5.2](https://github.com/KhronosGroup/VK-GL-CTS/releases/tag/vulkan-cts-1.1.5.2))

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.

**Comment by jekstrand** [comment]
Intel Linux driver support: https://gitlab.freedesktop.org/mesa/mesa/merge_requests/2236

**Comment by pdaniell-nv** [comment]
A native VK_KHR_timeline_semaphore implementation for NVIDIA GPUs can be found [here](https://developer.nvidia.com/vulkan-driver) for Windows and Linux.

**Comment by krOoze** [comment]
What is the "tolerance" of Timeline semaphores to signal-after-wait? Can I let them wait indefinitely?

**Comment by critsec** [comment]
Yes, the intent is that they can wait indefinitely. This is different from events, where the GPU would have to wait mid-command-buffer.

**Comment by krOoze** [comment]
@critsec nit: GPU could wait mid-command-buffer due to `pWaitDstStageMask`.

**Comment by mikew-lunarg** [comment]
Partial Validation coverage merged in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/1394

More to come (semaphore state changes), per [@jasuarez](https://github.com/jasuarez
)

**Comment by djdeath** [comment]
Layered implementation is at : https://github.com/KhronosGroup/Vulkan-ExtensionLayer/

We can probably tick that item off the list.

**Comment by TomOlson** [comment]
Validation is complete, so closing
