### ISSUE TITLE
Task list for VK_KHR_separate_depth_stencil_layouts release

### ISSUE THREAD

**Issue by pdaniell-nv** [KhronosGroup/Vulkan-Docs#1080]
The Vulkan 1.1.127 spec release includes the [VK_KHR_separate_depth_stencil_layouts](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/chap44.html#VK_KHR_separate_depth_stencil_layouts) extension.

This extension allows image memory barriers for depth/stencil images to have just one of the VK_IMAGE_ASPECT_DEPTH_BIT or VK_IMAGE_ASPECT_STENCIL_BIT aspect bits set, rather than require both. This allows their layouts to be set independently. To support depth/stencil images with different layouts for the depth and stencil aspects, the depth/stencil attachment interface has been updated to support a separate layout for stencil.

The task list for the VK_KHR_separate_depth_stencil_layouts extension release is:

- [x] Vulkan specification (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/chap44.html#VK_KHR_separate_depth_stencil_layouts)
- [x] Conformance tests (https://github.com/KhronosGroup/VK-GL-CTS/releases/tag/vulkan-cts-1.1.6.1)
- [x] Validation Layer (https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/9af77cd811107724152b56fb8bb7883a8f3ee29c)

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.

**Comment by pdaniell-nv** [comment]
NVIDIA driver support can be found here: https://developer.nvidia.com/vulkan-driver

**Comment by pdaniell-nv** [comment]
All tasks complete. Closing.
