### ISSUE TITLE
Task list for VK_KHR_performance_query release

### ISSUE THREAD

**Issue by alonorbach** [KhronosGroup/Vulkan-Docs#1091]
The Vulkan 1.1.128 spec release includes the [VK_KHR_performance_query](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/chap44.html#VK_KHR_performance_query) extension. 

This extension provides a cross-vendor common mechanism to expose performance metrics. These may be used to obtain data from a Vulkan device, typically a graphics card or SoC, to measure the workload demand and assess the impact of application modifications and optimizations. GPU vendor tools often provide such hardware counters, with the information tailored to their specific implementation. VK_KHR_performance_query provides a cross-vendor common mechanism to expose such counters, enabling third-party tools and in-engine profilers access in a standardized manner. Annotations are made in-line with existing Vulkan commands, so that it is possible to correlate specific bundles of work to the counter data captured – with the exact granularity dependent on hardware capabilities.

The task list for the VK_KHR_performance_query extension release is:

* [x] Vulkan specification ([VK_KHR_performance_query](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/chap44.html#VK_KHR_performance_query))
* [x] Validation layer (https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/1379)
* [x] Conformance tests: ([Vulkan CTS 1.1.6.2](https://github.com/KhronosGroup/VK-GL-CTS/releases/tag/vulkan-cts-1.1.6.2))
* [x] Blog post (https://www.khronos.org/blog/vulkan-releases-extension-to-expose-cross-vendor-performance-metrics)

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.

**Comment by djdeath** [comment]
An Intel/Mesa implementation of this extension is up for review here : https://gitlab.freedesktop.org/mesa/mesa/merge_requests/2775

**Comment by mikew-lunarg** [comment]
Validation layer merged https://github.com/KhronosGroup/Vulkan-ValidationLayers/commits/master

- https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/17881d2e045b643dcf26c7e22d9a615c4391e399
- https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/c742091f27f4553029f19837e1804ef46b4c8bdc

**Comment by alonorbach** [comment]
Closing issue as checklist complete
