### ISSUE TITLE
Task list for VK_EXT_tooling_info

### ISSUE THREAD

**Issue by Tobski** [KhronosGroup/Vulkan-Docs#1136]
The Vulkan 1.1.124 spec release includes the [VK_EXT_tooling_info](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VK_EXT_tooling_info) extension. When an error occurs during application development, a common question is "What tools are actually running right now?" This extension adds the ability to query that information directly from the Vulkan implementation.

The task list for the VK_EXT_tooling_info extension release is:

- [x] Vulkan specification (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VK_EXT_tooling_info)
- [x] RenderDoc (https://github.com/baldurk/renderdoc/issues/1632)
- [x] Validation layers (https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/1422)
- [x] Conformance tests (https://github.com/KhronosGroup/VK-GL-CTS/commit/5cf2e286fed90d00686775000853953b7d969e7f#diff-f886606aff6fb7904deebc72fc6670f8d0d1e70bbe04b5121911b089fb9632ed)

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.

**Comment by mark-lunarg** [comment]
Validation layer implementation is in work.

**Comment by mark-lunarg** [comment]
Validation work addressed by [Vulkan-ValidationLayers PR 1430](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/1430).

**Comment by krOoze** [comment]
@Tobski I think it is 1.1.130, not 1.1.124

**Comment by krOoze** [comment]
Could extension authors weigh in at https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/1430
we have bit of a discussion concerning the motivation for the extension, and so what should the Validation Layers report.

Also I would suggest establishing some rough style for `VkPhysicalDeviceToolPropertiesEXT::description` in the specification, so it is consistent across different tools.

**Comment by marty-johnson59** [comment]
@Tobski, here's another one for you.  Are we still waiting on CTS, or can we close this one?  If we are, is there an issue/owner for that task?  Thanks,

Marty

**Comment by Tobski** [comment]
This is done, CTS was made public with this commit: https://github.com/KhronosGroup/VK-GL-CTS/commit/5cf2e286fed90d00686775000853953b7d969e7f#diff-f886606aff6fb7904deebc72fc6670f8d0d1e70bbe04b5121911b089fb9632ed
