### ISSUE TITLE
Task list for Vulkan 1.2 release

### ISSUE THREAD

**Issue by TomOlson** [KhronosGroup/Vulkan-Docs#1162]
Vulkan 1.2 promotes 23 previously released Vulkan extensions into a new core specification, and adds other minor features to improve integration and ease of use. The complete list of new features can be found in Appendix D of the specification.

Vulkan is an ecosystem-driven API; the Vulkan and SPIR-V Working Groups define the specification, but the tools developers need to use the API come many teams across the Vulkan community. This issue tracks the state of the various documents and software artifacts needed to develop Vulkan 1.2 applications. As each item is made public, the task will be checked off below. When all tasks have been checked off, this issue will be closed and the Vulkan 1.2 release will be complete. Unless otherwise noted, the target release date for all items is on or before January 31, 2020.

The task list for the Vulkan 1.2 release is:
* [ ] Vulkan specification: https://www.khronos.org/registry/vulkan/#apispecs
* [ ] Vulkan headers:
* [ ] SPIRV-Tools:
* [ ] GLSL specification:
* [ ] glslang support:
* [ ] shaderc support:
* [ ] DXC support: target time frame: 1H 2020
* [ ] Validation Layer support: 
* [ ] Loader support:
* [ ] Tools support:
* [ ] Vulkan 1.2 SDK: 
* [ ] Vulkan 1.2 Conformance Test Suite (CTS):

Public installable Vulkan 1.2 drivers are available for download from the following vendors at the supplied URLs:
* **AMD:** _url_
* **Intel:** _url_
* **NVIDIA:** https://developer.nvidia.com/vulkan-driver

**Comment by hakzsam** [comment]
@TomOlson RADV MR https://gitlab.freedesktop.org/mesa/mesa/merge_requests/3410

**Comment by jekstrand** [comment]
Please, people, when you edit the task list, make sure you refresh your page immediately before hand.  Edits are getting lost left and right.  Either that or only @TomOlson should edit.

**Comment by jekstrand** [comment]
> @TomOlson RADV MR https://gitlab.freedesktop.org/mesa/mesa/merge_requests/3410

Both RADV and Intel Linux have now been merged into mesa master.

**Comment by dneto0** [comment]
SPIRV-Tools support:  https://github.com/KhronosGroup/SPIRV-Tools/pull/3137

**Comment by gnl21** [comment]
The glslang link looks wrong. The correct link is: https://github.com/KhronosGroup/glslang/pull/2058

**Comment by oddhack** [comment]
> Please, people, when you edit the task list, make sure you refresh your page immediately before hand. Edits are getting lost left and right. Either that or only @TomOlson should edit. We also appear (from what I'm seeing) to also be seeing a failure of the gitlab MR edit draft system where even if you do refresh stuff may get lost when you click "edit". You have to edit then discard then edit again to get a proper refresh.

Ditto. I keep trying to click the "headers" item as being done and it appears to reflect it, then I come back to the page later and it's back to unchecked. Seems like Github needs better locking around updates.

**Comment by johnkslang** [comment]
But, some of this could be browser caching, and the browser submitting older versions as the update, which GitHub can't control.

I re-clicked the headers for you, see how long it sticks.

**Comment by johnkslang** [comment]
> The glslang link looks wrong. The correct link is: KhronosGroup/glslang#2058

I'm sure I had 2058 to begin with, will carefully try updating again, once bots finish, with the new location.

**Comment by jekstrand** [comment]
> But, some of this could be browser caching, and the browser submitting older versions as the update, which GitHub can't control.

GitHub could make it so that an edit sends both the new text and what it thinks the old text was and do an `atomic_compare_exchange`.  You'd still have the ABA problem but at least it'd be better.  Also, they clearly have the history of all edits so they could send along which edit the current one is based on and reject if it doesn't match. :smile:

**Comment by oddhack** [comment]
> Also, they clearly have the history of all edits so they could send along which edit the current one is based on and reject if it doesn't match.  Even Bugzilla manages to get this right.

If only GH had access to some sort of "revision control" software that would keep track of changes and could tell when conflicts arose... naah, dreaming again.

**Comment by johnkslang** [comment]
I've update check-off items for Vulkan headers, glslang, and SPIRV-Tools, as well as the location of the latter two. All seem to be sticking and didn't seem to lose anything.

**Comment by dneto0** [comment]
Shaderc support in https://github.com/google/shaderc/pull/958

**Comment by krOoze** [comment]
> But, some of this could be browser caching, and the browser submitting older versions as the update, which GitHub can't control.

It can. Though I think the post editing is mostly meant for moderation, not for collaboration.

**Comment by TomOlson** [comment]
Definitely issues arising between browser caching and how the GH site behaves. But let's take those inside Khronos - not very interesting for people trying to track the Vulkan 1.2 release. Next time we do this, we'll find a different mechanism.

**Comment by dneto0** [comment]
Shaderc support has been merged into its master.  

@TomOlson:  please check the boxes for Shaderc and SPIRV-Tools

**Comment by malnasse** [comment]
@TomOlson please, remove the (Coming soon) next the AMD link. The driver has posted.

**Comment by alegal-arm** [comment]
CTS: https://github.com/KhronosGroup/VK-GL-CTS/releases/tag/vulkan-cts-1.2.1.0

**Comment by mikew-lunarg** [comment]
Validation layers: https://github.com/KhronosGroup/Vulkan-ValidationLayers/tree/v1.2.131

**Comment by TomOlson** [comment]
I have deleted the "GLSL specification" deliverable - turns out there are no updates.

**Comment by mikew-lunarg** [comment]
SDK released 2020-01-18

https://vulkan.lunarg.com/

**Comment by oddhack** [comment]
@TomOlson do you know who owns the DXC support checklist item and/or its status? Unlike the others there's no outward link to that repo, or owner, but it was supposed to be resolved 6 months ago. With that we could close this tracker.

**Comment by chirejaszy** [comment]
/system/framework/ext.jar
/system/framework/framework-oahl-backward-compatibility.jar
/system/framework/framework.jar
/system/lib/libplatformprotos.a. Notices for file(s):
/recovery/root/etc/mke2fs.conf
/system/etc/mke2fs.con
/system/lib/libext4_utils.a
/system/lib/libext4_utils.so
/system/lib/libf2fs_sparseblock.so

**Comment by marty-johnson59** [comment]
Closing as we're clearly done with this now:)
