### ISSUE TITLE
Task list for VK_KHR_shader_non_semantic_info release

### ISSUE THREAD

**Issue by pdaniell-nv** [KhronosGroup/Vulkan-Docs#1187]
The Vulkan 1.2.133 spec release includes the [VK_KHR_shader_non_semantic_info](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/chap44.html#VK_KHR_shader_non_semantic_info) extension. This extension adds Vulkan support for the [SPV_KHR_non_semantic_info](https://htmlpreview.github.io/?https://github.com/KhronosGroup/SPIRV-Registry/blob/master/extensions/KHR/SPV_KHR_non_semantic_info.asciidoc) SPIR-V extension.

The task list for the VK_KHR_shader_non_semantic_info extension release is:

* [x] Vulkan specification (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/chap44.html#VK_KHR_shader_non_semantic_info)
* [x] SPIRV-Registry (https://github.com/KhronosGroup/SPIRV-Registry/pull/56)
* [x] SPIRV-Headers (n/a - nothing new added)
* [x] SPIRV-Tools (https://github.com/KhronosGroup/SPIRV-Tools/pull/3110)
* [x] validation layer support (https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/1555)
* [x] SDK support (https://vulkan.lunarg.com/sdk/home; supported from version 1.2.135.0)
* [x] Conformance tests (https://github.com/KhronosGroup/VK-GL-CTS/tree/vulkan-cts-1.2.1.1)

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released. I expect to push most of this tomorrow.

**Comment by pdaniell-nv** [comment]
NVIDIA's latest Vulkan beta driver 442.36 (Windows) and 440.58.01 (Linux) implements this extension: https://developer.nvidia.com/vulkan-driver

**Comment by TomOlson** [comment]
CTS support added in version 1.2.1.1 (https://github.com/KhronosGroup/VK-GL-CTS/tree/vulkan-cts-1.2.1.1)

**Comment by TomOlson** [comment]
SDK support added in version 1.2.135.0 (https://vulkan.lunarg.com/sdk/home). Release  is now complete.
