### ISSUE TITLE
Task list for GL_EXT_debug_printf release

### ISSUE THREAD

**Issue by jeffbolznv** [KhronosGroup/Vulkan-Docs#1198]
We're releasing the GL_EXT_debug_printf GLSL extension, which allows printf-style logging from shaders. The implementation of the logging is primarily in the Vulkan Validation Layers, which convert the DebugPrintf SPIR-V instructions into stores to a temporary buffer, and then the strings can be outputted to the VVL message log or to stdout. There's no driver component to this extension, aside from some pre-existing features that the VVL implementation relies upon.

The task list for the release is:

* [x] SPIR-V NonSemantic.DebugPrintf extended instruction set (https://github.com/KhronosGroup/SPIRV-Registry/pull/61)
* [x] SPIRV-Header support (https://github.com/KhronosGroup/SPIRV-Headers/pull/145)
* [x] GLSL extension (https://github.com/KhronosGroup/GLSL/pull/108)
* [x] glslang implementation (https://github.com/KhronosGroup/glslang/pull/2098)
* [x] spirv-tools implementation (https://github.com/KhronosGroup/glslang/issues/3210)
* [x] Validation Layers implementation (https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/1645)
