### ISSUE TITLE
Task list for Vulkan Ray Tracing Provisional release

### ISSUE THREAD

**Issue by dgkoch** [KhronosGroup/Vulkan-Docs#1205]
Today the Khronos Vulkan Ray Tracing Task Sub Group (TSG) is announcing the public release of the provisional Vulkan Ray Tracing extensions.  See the [Press Release](https://khr.io/vkrayprovpress) for the announcement. 

The provisional version of Vulkan Ray Tracing that we are releasing today consists of 3 Vulkan, 2 SPIR-V, and 2 GLSL extensions. See the introductory [blog post](https://khr.io/vkrayprovblog) for more details and an overview of the functionality. 

Vulkan Specifications:
 - [VK_KHR_ray_tracing](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VK_KHR_ray_tracing)
 - [VK_KHR_deferred_host_operations](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VK_KHR_deferred_host_operations)
- [VK_KHR_pipeline_library](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VK_KHR_pipeline_library)

SPIR-V Specifications: 
- [SPV_KHR_ray_tracing](http://htmlpreview.github.io/?https://github.com/KhronosGroup/SPIRV-Registry/blob/master/extensions/KHR/SPV_KHR_ray_tracing.html)
- [SPV_KHR_ray_query](http://htmlpreview.github.io/?https://github.com/KhronosGroup/SPIRV-Registry/blob/master/extensions/KHR/SPV_KHR_ray_query.html)

GLSL Extension Specifications: 
- [GLSL_EXT_ray_tracing](https://github.com/KhronosGroup/GLSL/blob/master/extensions/ext/GLSL_EXT_ray_tracing.txt)
- [GLSL_EXT_ray_query](https://github.com/KhronosGroup/GLSL/blob/master/extensions/ext/GLSL_EXT_ray_query.txt)

Khronos welcomes feedback on the Vulkan Ray Tracing set of provisional specifications from the developer and content creation communities through the [Khronos Developer Slack](https://khr.io/slack) and [Vulkan GitHub Issues Tracker](https://khr.io/vkrayprovfeedback). Developers are also encouraged to share comments with their preferred hardware vendors. 
Your feedback is critical to enable us to finalize the first version of Vulkan Ray Tracing and make it genuinely meet your needs!

However, as this is a provisional release, some functionality is likely to change before the final release, consequently we are asking that driver vendors not ship it in production drivers and that ISVs not use the provisional version in production applications. 

**Applications using the provisional functionality must specifically opt into the interfaces being defined in the Vulkan header using one of the following techniques** (similar to the process for enabling the windowing system extensions), either by:
```
#define VK_ENABLE_BETA_EXTENSIONS
#include <vulkan/vulkan.h>
```
or by
```
#include <vulkan/vulkan_core.h>
#include <vulkan/vulkan_beta.h>
```
and should also check for the exact Vulkan extension version that they are expecting. 

Although we do not have a specific timeframe to announce for specification finalization, we want to move forward as quickly as we can, while ensuring the developer community is happy and we have a completed set of conformance tests and at least two implementations that can pass those tests. 

The task list for the Vulkan Ray Tracing provisional release is:
* [x] Vulkan specification: https://www.khronos.org/registry/vulkan/#apispecs (owner: @oddhack)
* [x] SPIR-V specifications: https://github.com/KhronosGroup/SPIRV-Registry/pull/64 (owner: @dgkoch, @johnkslang )
* [x] GLSL specifications: https://github.com/KhronosGroup/GLSL/pull/114 (owner: @dgkoch, @johnkslang )
* [x] Vulkan headers: in master (via https://github.com/KhronosGroup/Vulkan-Headers/pull/105) (owner: @oddhack)
* [x] SPIRV Headers: in master (via https://github.com/KhronosGroup/SPIRV-Headers/pull/149) (owner: @johnkslang )
* [x] SPIRV-Tools: in master (via https://github.com/KhronosGroup/SPIRV-Tools/pull/3235) (owner: @dneto0, @s-perron)
* [x] glslang support: (owner: @johnkslang )
  * [x] update to latest SPIR-V header
  * [x] GLSL_EXT_ray_tracing / SPV_KHR_ray_tracing - https://github.com/KhronosGroup/glslang/pull/2130 (owner: @alelenv, @dgkoch)
  * [x] GLSL_EXT_ray_query / SPV_KHR_ray_query - https://github.com/KhronosGroup/glslang/pull/2139 (owner: @Tobski )
  * [x] bug fix merged to master (via https://github.com/KhronosGroup/glslang/pull/2157)
  * [x] bug fix merged to master (via https://github.com/KhronosGroup/glslang/pull/2159)
  * [x] bug fix merged to master (via https://github.com/KhronosGroup/glslang/pull/2166)
* [x] shaderc support: (owner: @dneto0, @dgkoch)
  * [x] updates all tools for provisional ray tracing: in master (via google/shaderc#1006) (owner: @dnet0) 
  * [x] remove NV_EXTENSIONS define: in master (via https://github.com/google/shaderc/pull/1003) (owner: @dgkoch )
  * [x] pick up ray query support https://github.com/google/shaderc/pull/1018 
  * [x] known_good update (via https://github.com/google/shaderc/pull/1022)
  * [x] SDK-Candidiate DEP update (via https://github.com/google/shaderc/pull/1024)
  * [x] SDK-Candidate2 known good update (via https://github.com/google/shaderc/pull/1025 @dneto0) 
  * [x] SDK-Candidate-2 DEP update (via https://github.com/google/shaderc/pull/1027) (@dgkoch)
  * [x] SDK-Candidate-2 known_good update (via https://github.com/google/shaderc/pull/1033) (@dneto0)
* [x] DXC support: (owner: @alelenv, @Tobski ) 
  * [x] SPV_KHR_ray_tracing - in master (via https://github.com/microsoft/DirectXShaderCompiler/pull/2780) (owner: @alelenv )
  * [x] SPV_KHR_ray_query (https://github.com/microsoft/DirectXShaderCompiler/pull/2834) (owner: @jiaolu)
* [x] Validation Layer support: in master (via https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/1632) (owner: @jeffbolznv )
* [x] Vulkan SDK: https://vulkan.lunarg.com/sdk/home available now (owner: @mikew-lunarg )

Public installable Vulkan Ray Tracing Provisional (aka Beta) drivers are available for download from the following vendors at the supplied URLs:
* **AMD:** _url_
* **Intel:** _url_
* **NVIDIA:** https://developer.nvidia.com/vulkan-driver

**Comment by johnk** [comment]
I (johnk) am incorrectly listed as an owner of several items. You mean someone else I believe.

**Comment by dgkoch** [comment]
> I (johnk) am incorrectly listed as an owner of several items. You mean someone else I believe.

Sorry about that - fixed.

**Comment by tobias** [comment]
I find myself in the same situation - it looks like you have corrected all the tasks except `DXC support`.

**Comment by dgkoch** [comment]
> I find myself in the same situation - it looks like you have corrected all the tasks except `DXC support`.

Fixed as well - artifact of copy / pasting this from an internal tracker :-/

**Comment by Perksey** [comment]
What's with the deleted comments? If this issue is not to be commented on by the public, please can you lock and limit it so that we're not confused :P

**Comment by dgkoch** [comment]
> What's with the deleted comments? If this issue is not to be commented on by the public, please can you lock and limit it so that we're not confused :P

They were from unrelated people I'd accidentally tagged when I created the issue. I figured removing them was better so that they don't get all the notifications from this issue.  Now I'm going to have remove this thread so it's not cluttering things up too :-P

**Comment by mikew-lunarg** [comment]
I've updated SDK release to "first half of April", which depends on updates from other upstream repos.

**Comment by starbucksDave** [comment]
Slight error in this post: the macro to enable the beta extensions is `VK_ENABLE_BETA_EXTENSIONS` and not `VK_ENABLE_BETA_EXTENSIONS_KHR`. Sorry for the nitpick!

**Comment by Perksey** [comment]
@dgkoch Ah ok understood. As to not further clog up this issue with an unrelated thread, please can you use the `Hide` function instead of the `Delete` function (as I do still want to receive notifications as well as I want people to see why comments have been deleted)

**Comment by dgkoch** [comment]
> @dgkoch Ah ok understood. As to not further clog up this issue with an unrelated thread, please can you use the `Hide` function instead of the `Delete` function (as I do still want to receive notifications as well as I want people to see why comments have been deleted)

Done. I was unaware of that option. Thanks for pointing it out.

**Comment by dgkoch** [comment]
> Slight error in this post: the macro to enable the beta extensions is `VK_ENABLE_BETA_EXTENSIONS` and not `VK_ENABLE_BETA_EXTENSIONS_KHR`. Sorry for the nitpick!

🤦‍♂ Doh. That was a last minute change I forgot to reflect in the documentation. Corrected above (and soon in the blog post as well).

**Comment by dneto0** [comment]
I updated Shaderc's known-good branch with a build with necessary support from SPIRV-Tools, SPIRV-Headers, Glslang, and Shaderc itself.  https://github.com/google/shaderc/pull/1006

**Comment by dgkoch** [comment]
Validation layer support has been merged.

**Comment by dgkoch** [comment]
> I updated Shaderc's known-good branch with a build with necessary support from SPIRV-Tools, SPIRV-Headers, Glslang, and Shaderc itself. [google/shaderc#1006](https://github.com/google/shaderc/pull/1006)

@dneto0 can we get another shaderc update to include https://github.com/KhronosGroup/glslang/pull/2139 ?

**Comment by adam-sawicki-a** [comment]
A prototype support of VK_KHR_ray_tracing has been added to Vulkan Memory Allocator library on a separate branch:
https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/tree/VK_KHR_ray_tracing

Any feedback is welcomed, either in https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/issues/106 or as new issue tickets.

**Comment by dgkoch** [comment]
> > I updated Shaderc's known-good branch with a build with necessary support from SPIRV-Tools, SPIRV-Headers, Glslang, and Shaderc itself. [google/shaderc#1006](https://github.com/google/shaderc/pull/1006)
> 
> @dneto0 can we get another shaderc update to include [KhronosGroup/glslang#2139](https://github.com/KhronosGroup/glslang/pull/2139) ?

See https://github.com/google/shaderc/pull/1018

**Comment by mikew-lunarg** [comment]
SDK is live

https://vulkan.lunarg.com/sdk/home

**Comment by qq553563608** [comment]
my question is about AS host build.  I found I can assign a VkDeviceOrHostAddressKHR to scratchData in VkAccelerationStructureBuildGeometryInfoKHR in host AS build, but for binding memory to AS,there is not a VkDeviceOrHostAddressKHR, instead only a VkDeviceMemory in the VkBindAccelerationStructureMemoryInfoKHR, does that mean we don't need to bind memory when use host AS build, or we bind device memory when using host AS build?

**Comment by dgkoch** [comment]
DXC support for ray query has been merged. 
microsoft/DirectXShaderCompiler#2834

This completes the provisional release.
