### ISSUE TITLE
Task List for VK_EXT_robustness2

### ISSUE THREAD

**Issue by jeffbolznv** [KhronosGroup/Vulkan-Docs#1258]
The Vulkan 1.2.139 spec release includes the [VK_EXT_robustness2](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VK_EXT_robustness2) extension. This extension adds guarantees for bounds-checking buffer and image accesses that more closely match D3D behavior.

The task list for the VK_EXT_robustness2 extension release is:

* [x] Vulkan specification (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VK_EXT_robustness2)
* [x] validation layer (https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/1830)
* [x] Conformance tests ([vulkan-cts-1.2.3.2](https://github.com/KhronosGroup/VK-GL-CTS/releases/tag/vulkan-cts-1.2.3.2))

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.

**Comment by oddhack** [comment]
@jeffbolznv can this be closed? Everything has been checked off. If so the internal tracker (vulkan issue 2001) should probably also be closed.

**Comment by oddhack** [comment]
Woops, that was a question, not a statement - reopen after accidental close.

**Comment by jeffbolznv** [comment]
Closing, thanks.
