### ISSUE TITLE
Task list for VK_EXT_extended_dynamic_state

### ISSUE THREAD

**Issue by pdaniell-nv** [KhronosGroup/Vulkan-Docs#1297]
The Vulkan 1.2.145 spec release includes the [VK_EXT_extended_dynamic_state](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VK_EXT_extended_dynamic_state) extension. This extension adds a bunch more dynamic state so applications can potentially reduce the number of pipeline objects that they need to create.

The task list for the VK_EXT_extended_dynamic_state extension release is:

* [x] Vulkan specification (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VK_EXT_extended_dynamic_state)
* [x] Validation layer (WIP: https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/1977)
* [x] Conformance tests (https://github.com/KhronosGroup/VK-GL-CTS/releases/tag/vulkan-cts-1.2.3.0)

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.

**Comment by dgkoch** [comment]
Validation has been merged. Closing
