### ISSUE TITLE
Task List for VK_EXT_fragment_density_map2

### ISSUE THREAD

**Issue by mnetsch** [KhronosGroup/Vulkan-Docs#1317]
The Vulkan 1.2.146 spec release includes the VK_EXT_fragment_density_map2 extension. This extension is a maintenance extension to VK_EXT_fragment_density_map. It adds improvements to host latency and additional subsampled samplers limits.

The task list for the VK_EXT_fragment_density_map2 extension release is:

- [x]  Vulkan specification (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VK_EXT_fragment_density_map2)
- [x] Validation layer (https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2003)
- [x] Conformance tests (https://github.com/KhronosGroup/VK-GL-CTS/releases/tag/vulkan-cts-1.2.3.1)

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.
