### ISSUE TITLE
Task list for VK_KHR_copy_commands2

### ISSUE THREAD

**Issue by jackohound** [KhronosGroup/Vulkan-Docs#1366]
The Vulkan 1.2.154 spec release includes the [VK_KHR_copy_commands2](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VK_KHR_copy_commands2) extension.  This extension adds extensible versions of all the Vulkan copy commands.

The task list for the [VK_KHR_copy_commands2 extension release is:

* [x]   Vulkan specification ([VK_KHR_copy_commands2](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VK_KHR_copy_commands2))
* [x]   SPIRV specification (N/A)
* [x]   SPIRV headers change (N/A)
* [x]   SPIRV tools (N/A)
* [x]   Glslang (N/A)
* [x]   GLSL extension (N/A)
* [x]   Validation layer support (https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2209)
* [x]   Released in Conformance tests ([Vulkan CTS 1.2.4.1](https://github.com/KhronosGroup/VK-GL-CTS/releases/tag/vulkan-cts-1.2.4.1))
* [x]   Released in Vulkan SDK (1.2.154.0 SDK. No validation yet)

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.

**Comment by TomOlson** [comment]
Complete, closing
