### ISSUE TITLE
Task List for VK_EXT_shader_image_atomic_int64

### ISSUE THREAD

**Issue by Tobski** [KhronosGroup/Vulkan-Docs#1371]
The Vulkan 1.2.155 spec release includes the [VK_EXT_shader_image_atomic_int64](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_shader_image_atomic_int64.html) extension. This extension extends existing 64-bit integer atomic support to enable these operations on images as well.

The task list for the VK_EXT_shader_image_atomic_int64 extension release is:

* [x]   Vulkan specification (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_shader_image_atomic_int64.html)
* [x]   SPIRV specification (https://github.com/KhronosGroup/SPIRV-Registry/pull/81)
* [x]   SPIRV headers (https://github.com/KhronosGroup/SPIRV-Headers/pull/170)
* [x]   SPIRV tools (https://github.com/KhronosGroup/SPIRV-Tools/pull/3852)
* [x]   glslang (https://github.com/KhronosGroup/glslang/pull/2409)
* [x]   GLSL extension (https://github.com/KhronosGroup/GLSL/pull/136)
* [x]   Validation layer (https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2299)
* [x]   Conformance tests (https://github.com/KhronosGroup/VK-GL-CTS/releases/tag/vulkan-cts-1.2.5.0)
* [x]   Vulkan SDK Released (will be in December SDK)

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.

**Comment by johannesugb** [comment]
I'm writing here hoping that someone could shed some light on the following before I go ahead and create an issue over at the validaiton layer repository:

I get the following validation error:
> Validation Error: [ VUID-VkShaderModuleCreateInfo-pCode-04147 ] Object 0: handle = 0x2c8c8661c10, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x3d492883 | vkCreateShaderModule(): The SPIR-V Extension (SPV_EXT_shader_image_int64) was declared, but none of the requirements were met to use it. The Vulkan spec states: If pCode declares any of the SPIR-V extensions listed in the SPIR-V Environment appendix, one of the corresponding requirements must be satisfied (https://vulkan.lunarg.com/doc/view/1.3.243.0/windows/1.3-extensions/vkspec.html#VUID-VkShaderModuleCreateInfo-pCode-04147)

In GLSL, I have declared:
```
#extension GL_EXT_shader_image_int64                     : require
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
```

In host code, I have set `VkPhysicalDeviceFeatures::shaderInt64` to `VK_TRUE` and I've added a `VkPhysicalDeviceShaderImageAtomicInt64FeaturesEXT` structure into the device creation `pNext`-chain, where I've set `VkPhysicalDeviceShaderImageAtomicInt64FeaturesEXT::shaderImageInt64Atomics` to `VK_TRUE`.

I can't figure out what the validation error wants me to do in addition.
Am I missing something?

**Comment by spencer-lunarg** [comment]
@johannesugb the spec has a table for this

![image](https://github.com/KhronosGroup/Vulkan-Docs/assets/115671160/27a6438a-580a-45ae-9f1a-ab9901fc3ebb)

Which means you might be missing adding the `VK_EXT_shader_image_atomic_int64` extension at `vkCreateDevice`

https://github.com/KhronosGroup/Vulkan-Guide/blob/main/chapters/enabling_extensions.adoc

**Comment by johannesugb** [comment]
> Which means you might be missing adding the `VK_EXT_shader_image_atomic_int64` extension at `vkCreateDevice`

Oh man, I looked at everything but this. Indeed the extension was missing.      
Thank you!

**Comment by spencer-lunarg** [comment]
it is a TODO of mine instead of

>  but none of the requirements were met to use it.

to actually just print what those requirements are
