### ISSUE TITLE
Task List for VK_KHR_fragment_shading_rate

### ISSUE THREAD

**Issue by Tobski** [KhronosGroup/Vulkan-Docs#1384]
The Vulkan 1.2.158 spec release includes the [VK_KHR_fragment_shading_rate](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_fragment_shading_rate.html) extension. This extension adds the ability to change the rate at which fragments are shaded. Rather than the usual single fragment invocation for each pixel covered by a primitive, multiple pixels can be shaded by a single fragment shader invocation.

The task list for the VK_KHR_fragment_shading_rate extension release is:

* [x]   Vulkan specification [VK_KHR_fragment_shading_rate](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_fragment_shading_rate.html)
* [x]   SPIRV specification [SPV_KHR_fragment_shading_rate](http://htmlpreview.github.io/?https://github.com/KhronosGroup/SPIRV-Registry/blob/master/extensions/KHR/SPV_KHR_fragment_shading_rate.html)
* [x]   SPIRV headers (https://github.com/KhronosGroup/SPIRV-Headers/pull/172)
* [x]   SPIRV tools (https://github.com/KhronosGroup/SPIRV-Tools/pull/3943)
* [x]   glslang (https://github.com/KhronosGroup/glslang/pull/2428)
* [x]   GLSL extension (https://github.com/KhronosGroup/GLSL/pull/137)
* [x]   Validation layer (https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2266)
* [x]   Conformance tests
* [x]   DirectX Shader Compiler (https://github.com/microsoft/DirectXShaderCompiler/pull/3664)

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.

**Comment by pdaniell-nv** [comment]
Support for NVIDIA Turing and Ampere products can be found in our 457.00 (Windows) and 455.26.02 (Linux) drivers here: developer.nvidia.com/vulkan-driver.

**Comment by SaschaWillems** [comment]
Already posted this at the accompanying validation layer issue:

Is there a reason for `VkPhysicalDeviceFragmentShadingRateKHR` to have an ´sType` member? That structure type is only used in a get function, but with it having an `sType` member needing initialization (to silence validation), it makes up from some odd code.

Take this for example:

```cpp
std::vector<VkPhysicalDeviceFragmentShadingRateKHR> fragment_shading_rates{};
uint32_t fragment_shading_rate_count = 0;
vkGetPhysicalDeviceFragmentShadingRatesKHR(device, &fragment_shading_rate_count, nullptr);
if (fragment_shading_rate_count > 0)
{
	fragment_shading_rates.resize(fragment_shading_rate_count);
	vkGetPhysicalDeviceFragmentShadingRatesKHR(device, &fragment_shading_rate_count, fragment_shading_rates.data());
}
```

This will trigger validation layer message for all entries in the `fragment_shading_rates` vector. So to silence these and adhere to the valid usage, one would have to set the `sType`  for each entry in that vector. This looks a bit odd and counter-intuitive.

**Comment by Tobski** [comment]
@SaschaWillems I've moved your question over to a dedicated issue, and I'll post some comments there too.

**Comment by marty-johnson59** [comment]
Doing some year-end house-cleaning on open public issues...   @Tobski I see CTS isn't checked here.  Is that still needed - and if so, is there an issue/owner for that task?  Thanks,

Marty

**Comment by Tobski** [comment]
@marty-johnson59 CTS is on track to be updated as the tests are merged internally, but they've not made it to a public release yet. Once they are on GitHub we'll check this off.

**Comment by Tobski** [comment]
With https://github.com/microsoft/DirectXShaderCompiler/pull/3664 merged finally, this can now be closed.
