### ISSUE TITLE
Task List for VK_KHR_shader_terminate_invocation

### ISSUE THREAD

**Issue by critsec** [KhronosGroup/Vulkan-Docs#1385]
The Vulkan 1.2.158 spec release includes the [VK_KHR_shader_terminate_invocation](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_shader_terminate_invocation.html) extension. This extension adds Vulkan support for the [SPV_KHR_terminate_invocation](https://htmlpreview.github.io/?https://github.com/KhronosGroup/SPIRV-Registry/blob/master/extensions/KHR/SPV_KHR_terminate_invocation.html) SPIR-V extension, which allows terminating a fragment shader invocation without the ambiguous behavior of the existing `OpKill` instruction. Future GLSL compilers will rely on this extension for implementing the `discard` statement.

The task list for the VK_KHR_shader_terminate_invocation extension release is:

* [x]   Vulkan specification [VK_KHR_shader_terminate_invocation](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_shader_terminate_invocation.html)
* [x]   SPIRV specification [SPV_KHR_terminate_invocation](http://htmlpreview.github.io/?https://github.com/KhronosGroup/SPIRV-Registry/blob/master/extensions/KHR/SPV_KHR_terminate_invocation.html)
* [x]   SPIRV headers (https://github.com/KhronosGroup/SPIRV-Headers/pull/163)
* [x]   SPIRV tools (https://github.com/KhronosGroup/SPIRV-Tools/pull/3568)
* [x]   glslang (https://gitlab.khronos.org/vulkan/vulkan/-/issues/2276)
* [X]   Validation layer (https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2299)
* [x]   Conformance tests (https://github.com/KhronosGroup/VK-GL-CTS/releases/tag/vulkan-cts-1.2.5.0)

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.

**Comment by procedural** [comment]
> which allows terminating a fragment shader invocation without the ambiguous behavior of the existing OpKill instruction.

wat.

**Comment by polarina** [comment]
I do not understand how `OpKill` is ambiguous. It is a terminating instruction, it is not possible to "continue" execution unlike with the `OpDemoteToHelperInvocationEXT` instruction.

Even the description of `OpTerminateInvocation` is identical to that of `OpKill`. What is the purpose of this extension?

**Comment by jeffbolznv** [comment]
OpKill was meant to be unambiguous, but before "demote" was added (https://github.com/KhronosGroup/Vulkan-Docs/issues/990) many HLSL ports were using OpKill in a way that required invocations to stay alive in order to get correct implicit derivatives. Then most compilers had to treat OpKill like OpDemoteToHelperInvocation to make all those apps render correctly, and we end up with implementation-dependent behavior of OpKill, and non-conformant behavior of OpKill. Now we have two instructions with clear behavior (terminate and demote), and OpKill is (or should/will be) deprecated.

**Comment by marty-johnson59** [comment]
Doing some year-end house-cleaning on open public issues...  @critsec any updates on this one?  Looks like there's still confusion on how this relates to OpKill?  Are those questions resolved?   Also, I see Validation isn't checked.  Is that needed?  Is there an issue/owner for that?  Thanks

Marty
