### ISSUE TITLE
Task list for Vulkan Ray Tracing release

### ISSUE THREAD

**Issue by dgkoch** [KhronosGroup/Vulkan-Docs#1402]
Today, Khronos® has released the final versions of the set of Vulkan®, GLSL and SPIR-V extension specifications that seamlessly integrate ray tracing into the existing Vulkan framework. For more details see the [blog post](https://www.khronos.org/blog/vulkan-ray-tracing-final-specification-release).

Vulkan Specifications:
 - [VK_KHR_acceleration_structure](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VK_KHR_accelertion_structure)
 - [VK_KHR_ray_tracing_pipeline](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VK_KHR_ray_tracing_pipeline)
 - [VK_KHR_ray_query](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VK_KHR_ray_query)
 - [VK_KHR_deferred_host_operations](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VK_KHR_deferred_host_operations)
 - [VK_KHR_pipeline_library](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VK_KHR_pipeline_library)

SPIR-V Specifications: 
- [SPV_KHR_ray_tracing](http://htmlpreview.github.io/?https://github.com/KhronosGroup/SPIRV-Registry/blob/master/extensions/KHR/SPV_KHR_ray_tracing.html)
- [SPV_KHR_ray_query](http://htmlpreview.github.io/?https://github.com/KhronosGroup/SPIRV-Registry/blob/master/extensions/KHR/SPV_KHR_ray_query.html)

GLSL Extension Specifications: 
- [GLSL_EXT_ray_tracing](https://github.com/KhronosGroup/GLSL/blob/master/extensions/ext/GLSL_EXT_ray_tracing.txt)
- [GLSL_EXT_ray_query](https://github.com/KhronosGroup/GLSL/blob/master/extensions/ext/GLSL_EXT_ray_query.txt)
- [GLSL_EXT_ray_flags_primitive_culling.txt](https://github.com/KhronosGroup/GLSL/blob/master/extensions/ext/GLSL_EXT_ray_flags_primitive_culling.txt)

The task list for the Vulkan Ray Tracing provisional release is:
* [x] Vulkan specification: https://www.khronos.org/registry/vulkan/#apispecs (owner: @oddhack)
  - 1.2.162
* [x] SPIR-V specifications: https://github.com/KhronosGroup/SPIRV-Registry/ (owner: @dgkoch)
   - https://github.com/KhronosGroup/SPIRV-Registry/pull/86
* [x] GLSL specifications: https://github.com/KhronosGroup/GLSL/ (owner: @dgkoch)
   - https://github.com/KhronosGroup/GLSL/pull/144
* [x] Vulkan headers: https://github.com/KhronosGroup/Vulkan-Headers/ (owner: @oddhack)
   - https://github.com/KhronosGroup/Vulkan-Headers/pull/165
* [x] SPIRV Headers: https://github.com/KhronosGroup/SPIRV-Headers/ (owner: @dgkoch )
  - https://github.com/KhronosGroup/SPIRV-Headers/pull/182
* [x] SPIRV-Tools: https://github.com/KhronosGroup/SPIRV-Tools/ (owner: @dgkoch)
  - https://github.com/KhronosGroup/SPIRV-Tools/pull/4027, KhronosGroup/SPIRV-Tools#4028
* [x] glslang support: (owner: @johnkslang)
  * [x] update to latest SPIR-V header (included in below PR)
  * [x] final extension support - https://github.com/KhronosGroup/glslang/ (owner: @dgkoch)
     - https://github.com/KhronosGroup/glslang/pull/2466
* [x] shaderc support: (owner: @dneto0)
  * [x] updates all tools for ray tracing: (owner: @dneto0) 
     - https://github.com/google/shaderc/pull/1156
  * [x] known_good update (owner: @dneto0)
* [x] DXC support: (owner: @jiaolu, @Tobski ) 
  * [x] Updates to final semantics: https://github.com/microsoft/DirectXShaderCompiler/ (owner: @jiaolu)
    - https://github.com/microsoft/DirectXShaderCompiler/pull/3279
* [x] Validation Layer support: https://github.com/KhronosGroup/Vulkan-ValidationLayers/ (owner: @shannon-lunarg)
    - https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2346
* [x] Conformance Tests (owner: @alegal-arm)
    - https://github.com/KhronosGroup/VK-GL-CTS/releases/tag/vulkan-cts-1.2.5.0 
* [x] Vulkan SDK: https://vulkan.lunarg.com/sdk/home available now (owner: @KarenGhavam-lunarG)

Public installable Vulkan Ray Tracing Beta drivers are available for download from the following vendors at the supplied URLs:
* **AMD:** 
  - [Beta](https://www.amd.com/en/support/kb/release-notes/rn-rad-win-20-11-2-vrt-beta)
  - [Production](https://gpuopen.com/vulkan-ray-tracing-extensions/)
* **Intel:** The ray tracing extensions will be supported by Intel Xe-HPG GPUs, available in 2021, with driver support provided via the regular driver update process.
* **NVIDIA:** 
  - [Beta](https://developer.nvidia.com/vulkan-driver)
  - [Production](https://news.developer.nvidia.com/vulkan-ray-tracing-production-drivers-and-quake-ii-rtx-cross-vendor-extensions/)

**Comment by dneto0** [comment]
Shaderc internal dependencies file (DEPS) has been rolled forward.   https://github.com/google/shaderc/pull/1156 was merged

I plan to wait for SPIRV-Tools 'stable' update later this week  before updating its known_good

**Comment by alegal-arm** [comment]
CTS: https://github.com/KhronosGroup/VK-GL-CTS/releases/tag/vulkan-cts-1.2.5.0

**Comment by dgkoch** [comment]
The SDK has now been released, and both AMD and NVIDIA are shipping production drivers. 

- Press Release: https://www.khronos.org/news/press/vulkan-sdk-tools-and-drivers-are-ray-tracing-ready
- New Holochip blog: https://www.khronos.org/blog/holochip-develops-breakthrough-light-field-rendering-using-vulkan-ray-tracing
- Update Ray Tracing blog: https://www.khronos.org/blog/ray-tracing-in-vulkan
