### ISSUE TITLE
Task List for VK_KHR_synchronization2

### ISSUE THREAD

**Issue by Tobski** [KhronosGroup/Vulkan-Docs#1454]
The Vulkan 1.2.170 spec release includes the [VK_KHR_synchronization2](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_synchronization2.html) extension. This extension modifies the original core synchronization APIs to simplify the interface and improve usability of these APIs. It also adds new pipeline stage and access flag types that extend into the 64-bit range, as we have run out within the 32-bit range. The new flags are identical to the old values within the 32-bit range, with new stages and bits beyond that. See the [extension appendix](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_synchronization2.html) for details on the changes.

The task list for the VK_KHR_synchronization2extension release is:

* [x]   API specification: [VK_KHR_synchronization2](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_synchronization2.html)
* [x]   Guide (https://github.com/KhronosGroup/Vulkan-Guide/blob/master/chapters/extensions/VK_KHR_synchronization2.md)
* [x]   SDK Release (https://khr.io/w2)
  * [x]   Validation (https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2561)
  * [x]   Emulation (KhronosGroup/Vulkan-ExtensionLayer#44)
* [x]   Conformance (Added in CTS 1.2.5: https://github.com/KhronosGroup/VK-GL-CTS/commit/3a0dd45db3eac72695a49a056b8c02c1fceff091)
* [x]  Synchronization Examples (https://github.com/KhronosGroup/Vulkan-Docs/wiki/Synchronization-Examples)

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.

**Comment by Tobski** [comment]
AMD has developer drivers available with sync2 support, available here: https://www.amd.com/en/support/kb/release-notes/rn-rad-21-2-2-vrt-beta

**Comment by pdaniell-nv** [comment]
The are NVIDIA drivers supporting VK_KHR_synchronization2 here: https://developer.nvidia.com/vulkan-driver.

**Comment by jeremyg-lunarg** [comment]
The SDK "Emulation" layer is in this pull request: https://github.com/KhronosGroup/Vulkan-ExtensionLayer/pull/44

Merging of Validation is in progress. It will involve several pull requests across several repos. I'll spare you the details unless you really really want them here.

**Comment by jeremyg-lunarg** [comment]
https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2561 is most likely the final PR for synchronization2 support in ValidationLayers.

**Comment by jeremyg-lunarg** [comment]
> [KhronosGroup/Vulkan-ValidationLayers#2561](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2561) is most likely the final PR for synchronization2 support in ValidationLayers.

I mean, other than the inevitable bug fixes...  But both the ExtensionLayer and ValidationLayer changes above are merged.

**Comment by sfricke-samsung** [comment]
Got a few upvotes on Guide entry and no outstanding issues, merged it in, can always adjust if issues are found, updated link above as well

**Comment by Tobski** [comment]
This extension is now fully released, so closing.
