### ISSUE TITLE
Task List for VK_KHR_zero_initialize_workgroup_memory

### ISSUE THREAD

**Issue by critsec** [KhronosGroup/Vulkan-Docs#1457]
The Vulkan 1.2.168 spec release includes the [VK_KHR_zero_initialize_workgroup_memory](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_zero_initialize_workgroup_memory.html) extension. This extension allows shader `Workgroup` variables to be initialized with the null constant initializer, which can make it easier for implementations to efficiently zero-initialize workgroup memory.

The task list for the VK_KHR_zero_initialize_workgroup_memory extension release is:

* [x] Vulkan specification [VK_KHR_zero_initialize_workgroup_memory](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_zero_initialize_workgroup_memory.html)
* [x] SPIRV tools (https://github.com/KhronosGroup/SPIRV-Tools/pull/4124)
* [x] glslang (https://github.com/KhronosGroup/glslang/pull/2511)
* [x] Validation layer (n/a, handled by spirv-val)
* [x] Conformance tests

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.
