### ISSUE TITLE
Task List for VK_KHR_workgroup_memory_explicit_layout

### ISSUE THREAD

**Issue by cmarcelo** [KhronosGroup/Vulkan-Docs#1462]
The Vulkan 1.2.168 spec release includes the VK_KHR_workgroup_memory_explicit_layout extension.  This extension adds Vulkan support for the [SPV_KHR_workgroup_memory_explicit_layout](http://htmlpreview.github.io/?https://github.com/KhronosGroup/SPIRV-Registry/blob/master/extensions/KHR/SPV_KHR_workgroup_memory_explicit_layout.html) SPIR-V extension, which allows shaders to explicitly define the layout of Workgroup storage class memory and create aliases between variables from that storage class in a compute shader.

The task list for the VK_KHR_workgroup_memory_explicit_layout extension release is:

- [x] Vulkan specification [VK_KHR_workgroup_memory_explicit_layout](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VK_KHR_workgroup_memory_explicit_layout)
- [x] SPIRV specification (https://github.com/KhronosGroup/SPIRV-Registry/pull/94)
- [x] SPIRV headers (https://github.com/KhronosGroup/SPIRV-Headers/pull/192)
- [x] SPIRV tools (https://github.com/KhronosGroup/SPIRV-Tools/pull/4128)
- [x] glslang (https://github.com/KhronosGroup/glslang/pull/2512)
- [x] GLSL extension (https://github.com/KhronosGroup/GLSL/pull/150)
- [x] Validation layer (KhronosGroup/Vulkan-ValidationLayers#2299)
- [x] Conformance tests
- [x] Vulkan SDK Released (target: March 1st SDK)

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.

**Comment by marty-johnson59** [comment]
All items are released - closing this issue
