### ISSUE TITLE
Task list for VK_EXT_color_write_enable release

### ISSUE THREAD

**Issue by selcott** [KhronosGroup/Vulkan-Docs#1506]
Release Task List

The VK_EXT_color_write_enable extension allows for selectively enabling and disabling writes to output color attachments via a pipeline dynamic state.

The intended use cases for this new state are mostly identical to those of colorWriteMask, such as selectively disabling writes to avoid feedback loops between subpasses or bandwidth savings for unused outputs. By making the state dynamic, one additional benefit is the ability to reduce pipeline counts and pipeline switching via shaders that write a superset of the desired data of which subsets are selected dynamically. The reason for a new state, colorWriteEnable, rather than making colorWriteMask dynamic is that, on many implementations, the more flexible per-channel semantics of the colorWriteMask state cannot be made dynamic in a performant manner.

The task list for the VK_EXT_color_write_enable release is:

 - [x] Vulkan Specification:  https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/chap50.html#VK_EXT_color_write_enable
 - [x] Conformance tests released: https://github.com/KhronosGroup/VK-GL-CTS/releases/tag/vulkan-cts-1.2.6.1
 - [x] SDK released: https://vulkan.lunarg.com 
     - [x] Validation layer: 
     - [ ] Emulation layer: <N/A>
 - [x] Vulkan Guide:  https://github.com/KhronosGroup/Vulkan-Guide/blob/master/chapters/dynamic_state.adoc
 - [x] API Examples:  

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.

**Comment by marty-johnson59** [comment]
Added to the dynamic chapter in guide
