### ISSUE TITLE
Task list for VK_EXT_extended_dynamic_state2

### ISSUE THREAD

**Issue by vkushwaha-nv** [KhronosGroup/Vulkan-Docs#1510]
This extension allows the following states to be dynamic that will help reduce the number of pipeline objects.
* Specifying logicOp
* Specifying primitive restart enable
* Enabling/Disabling rasterization discard
* depth bias enable/disable 
* Specify number of patch control points

The task list for the VK_EXT_vertex_input_dynamic_state release is:

- [ ]  Vulkan Specification: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_extended_dynamic_state2.html
- [ ]  Conformance tests released
- [ ]  SDK released
     - [ ]  Validation layer: KhronosGroup/Vulkan-ValidationLayers#2724

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.

**Comment by martty** [comment]
Not sure if the right forum, but can I ask what is the motivation behind the depth bias enable/disable dynamic state?

**Comment by Degerz** [comment]
I think depth bias is a dynamic state on Mantle. Patch control points and logic ops are static states on Mantle.

**Comment by vkushwaha-nv** [comment]
For two reasons:
a. It can potentially reduce the number of pipelines that need to be created.
b. It was easy for all IHVs that wanted to support VK_EXT_extended_dynamic_state2 to support this.
