### ISSUE TITLE
Task list for VK_EXT_provoking_vertex release

### ISSUE THREAD

**Issue by critsec** [KhronosGroup/Vulkan-Docs#1527]
When flat shading, one of the vertices in a primitive supplies the flat-shaded attribute value. This vertex is known as the provoking vertex. Vulkan and some other APIs use a first-vertex convention, while OpenGL ES uses a last-vertex convention, and OpenGL supports both (last-vertex is default).

This extension allows changing the provoking vertex convention between Vulkan’s default convention (first vertex) and OpenGL’s convention (last vertex). It is intended for use by API-translation layers that implement APIs like OpenGL on top of Vulkan and need to match the source API’s provoking vertex convention. Applications using Vulkan directly should use Vulkan’s default convention.

When transform feedback is available, this extension also provides more guarantees about the order that vertices within a primitive will be written to transform feedback buffers, so that flat shading can be preserved through transform feedback cycles.

The task list for the VK_EXT_provoking_vertex release is:

 - [x] Vulkan Specification: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_provoking_vertex.html
 - [x] Conformance tests released: https://github.com/KhronosGroup/VK-GL-CTS/releases/tag/vulkan-cts-1.2.7.0
 - [x] SDK released: Vulkan SDK 1.2.182.0 (July 5, 2021)
     - [x] Validation layer: https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2766
 - [x] Vulkan Guide:  https://github.com/KhronosGroup/Vulkan-Guide/blob/master/chapters/extensions/translation_layer_extensions.md#vk_ext_provoking_vertex

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.
