### ISSUE TITLE
Release Task List for VK_KHR_shader_subgroup_uniform_control_flow

### ISSUE THREAD

**Issue by alan-baker** [KhronosGroup/Vulkan-Docs#1552]
Release Task List

Title of issue:  Task list for  release

The task list for the  release is:

 - [x] Vulkan Specification:  https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_shader_subgroup_uniform_control_flow.html
 - [x] SPIRV specification:  https://github.com/KhronosGroup/SPIRV-Registry/pull/114
 - [x] SPIRV Headers:  https://github.com/KhronosGroup/SPIRV-Headers/pull/213
 - [x] SPIRV tools released: https://github.com/KhronosGroup/SPIRV-Tools/pull/4318
 - [x] GLSL extension: https://github.com/KhronosGroup/GLSL/pull/160
 - [x] Glslang implementation: https://github.com/KhronosGroup/glslang/pull/2659 
 - [x] Conformance tests released: 
 - [x] SDK released: 

     - [x] Validation layer: 
     - [x] Emulation layer: 

 - [x] Vulkan Guide:  https://github.com/KhronosGroup/Vulkan-Guide/pull/118
 - [ ] API Examples: 
 - [ ] Shaderc:  
 - [ ] HLSL mapping:
 - [ ] HLSL glslang support:
 - [ ] HLSL DXC support: 

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.
