### ISSUE TITLE
Task list for VK_EXT_global_priority_query release

### ISSUE THREAD

**Issue by zhangyiwei** [KhronosGroup/Vulkan-Docs#1553]
This device extension allows applications to query the global queue priorities supported by a queue family.
- It allows implementations to report which global priority levels are treated differently by the implementation
  - No longer silently map multiple requested global priority levels to the same internal priority.
  - No longer use device creation failure to signal that a requested priority is not supported.
- It is intended primarily for use by system integration along with certain platform-specific priority enforcement rules.

The task list for the `VK_EXT_global_priority_query` release is:

 - [x] Vulkan Specification:  https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_global_priority_query.html
 - [x] Conformance tests released: https://github.com/KhronosGroup/VK-GL-CTS/commit/0d5d078205373b41e4b7c5bfa02c4c07c908c34e
 - [x] SDK released: July 5, 2021 Vulkan SDK 1.2.182.0 Release
     - [x] Validation layer: no new VUs

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.

**Comment by zhangyiwei** [comment]
@marty-johnson59

**Comment by zhangyiwei** [comment]
Closed as fully released
