### ISSUE TITLE
Task list for VK_KHR_portability_subset release

### ISSUE THREAD

**Issue by marty-johnson59** [KhronosGroup/Vulkan-Docs#1608]
Release Task List for VK_KHR_portability_subset release

The Vulkan Portability extension provides standardized queries for available layered API functionality.

Vulkan Portability layered libraries can provide extensive Vulkan functionality when running over other modern 3D APIs. However, if there are parts of Vulkan that cannot be supported at close-to-native performance levels due to the underlying API, then a Vulkan Portability implementation ships with the Vulkan Portability Extension to indicate that the layered implementation in not fully Vulkan conformant, and provide a consistent way to query what API functionality is provided by that layered implementation.

Vulkan Portability is extending the Vulkan conformance test suite to enable a layered implementation to ensure that all functionality reported to be present by the Vulkan Portability Extension is conformant. Vulkan Portability implementations that pass the conformance process are enabled to use the Vulkan Portability trademark and logo.

The Vulkan Portability extension is currently provisional and is planned for final release in the near future.  The task list for the Vulkan Portability extension final release includes:

 - [x] Vulkan Provisional Specification:  https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/chap50.html#VK_KHR_portability_subset 
 - [ ] Vulkan Portability Extension Specification 1.0:
 - [ ] Vulkan Loader with Portability support:
 - [ ] Vulkan extension: Inclusion/exclusion of Vulkan Compliant implementations query
 - [ ] Conformance tests released: 
 - [ ] SDK released: 
 - [ ] Validation layer: 
 - [ ] Vulkan Guide:  
 - [ ] API Examples:  
 - [ ] MoltenVK, gfx-rs, and devsim:
 - [ ] Samples:

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.

**Comment by haasn** [comment]
What's the status on this? Current release versions of MoltenVK already rely on this extension and force clients to enable it, can it be moved out of beta status?

**Comment by krOoze** [comment]
Bump. Same question as @haasn.

Since this may come up occasionally with various other de-extension, would it be better if `VkPhysicalDevicePortabilitySubsetFeatures` was an array of enum-bool pairs, where the enumerants can be updated without breaking compatibility. An application would be required to crawl through that array and if it encounters an enumerant it does not know, it should filter that driver out.
