### ISSUE TITLE
Task list for VK_EXT_load_store_op_none release

### ISSUE THREAD

**Issue by ShabbyX** [KhronosGroup/Vulkan-Docs#1620]
This extension provides two new render pass operations: `LOAD_OP_NONE` and `STORE_OP_NONE`. These operations are particularly useful on tile-based rendering (TBR) architectures where they save bandwidth by avoiding unnecessary loads and stores of framebuffer data. Outside TBR architectures, they can help simply synchronization of read-only attachments.

- `STORE_OP_NONE`: This store op indicates to the driver that an attachment was not written to during a render pass, and thus it's not required to be updated after the render pass. Traditionally, `STORE_OP_STORE` had to be used in such a situation, which is detrimental to performance on TBR architectures.

   Note that `STORE_OP_DONT_CARE` cannot be used as that invalidates the contents of the image; even if the contents are not actually destroyed, a driver for example would be allowed to change `LOAD_OP_LOAD` to `LOAD_OP_DONT_CARE` in the next render pass (rendering to the same image) as the contents are invalid anyway.

   Furthermore, both `STORE_OP_STORE` and `STORE_OP_DONT_CARE` are write operations as far as synchronization is concerned, requiring memory barriers where none was really needed; `STORE_OP_NONE` has no such requirement.

- `LOAD_OP_NONE`: This load op indicates to the driver that an attachment does not need loading. This may seem unnecessary, as `LOAD_OP_DONT_CARE` serves a similar purpose (and could be more efficient), but serves a specific use case. If the attachment is entirely unused by the render pass, `LOAD_OP_NONE` can be used in conjunction with `STORE_OP_NONE` to avoid spending bandwidth loading from this attachment while still preserving its contents.

   Note that `LOAD_OP_DONT_CARE` cannot be used in such a case as it invalidates the contents of the attachment. Under normal circumstances, this is still unnecessary; the application could simply not specify this attachment in the framebuffer in the first place. In some applications however, it is unknown whether an attachment may or may not be used during the render pass until the render pass is finished, at which point it's impossible to change the framebuffer. This op serves such applications, such as an OpenGL emulation layer.

The task list for the VK_EXT_load_store_op_none release is:

 - [x] Vulkan Specification: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_load_store_op_none.html
 - [x] Conformance tests released: Added in [CTS 1.2.8.0](https://github.com/KhronosGroup/VK-GL-CTS/releases/tag/vulkan-cts-1.2.8.0): https://github.com/KhronosGroup/VK-GL-CTS/commit/74960221b0e09b87c6ed10964b99b90490131034
 - [x] SDK released: [Vulkan SDK 1.2.189.0](https://vulkan.lunarg.com/sdk/home)
     - [x] Validation layer: https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/3174

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.
