### ISSUE TITLE
Task list for VK_KHR_shader_integer_dot_product release

### ISSUE THREAD

**Issue by kpet** [KhronosGroup/Vulkan-Docs#1626]
This extension adds support for the integer dot product SPIR-V instructions defined in SPV_KHR_integer_dot_product. These instructions are particularly useful for neural network inference and training but find uses in other general purpose compute applications as well.

A primary use case for the extension is to support ML toolchains that generate SPIR-V directly. We do intend to provide GLSL and HLSL support fairly soon, but that is a lower priority here than it is for most other extensions.

The task list for the VK_KHR_shader_integer_dot_product release is:

 - [x] Vulkan Specification:  https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_shader_integer_dot_product.html
 - [x] SPIRV specification: http://htmlpreview.github.io/?https://github.com/KhronosGroup/SPIRV-Registry/blob/master/extensions/KHR/SPV_KHR_integer_dot_product.html
 - [x] SPIRV Headers:  https://github.com/KhronosGroup/SPIRV-Headers/pull/220
 - [x] SPIRV tools released: https://github.com/KhronosGroup/SPIRV-Tools/pull/4327
 - [x] GLSL extension: https://github.com/KhronosGroup/GLSL/pull/195
 - [ ] Glslang implementation:  
 - [x] Conformance tests released: https://github.com/KhronosGroup/VK-GL-CTS/releases/tag/vulkan-cts-1.3.1.0
 - [x] SDK released: Version 1.2.198.0 (December 2021)
 - [ ] Shaderc:  
 - [ ] HLSL DXC support: 

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.

**Comment by spencer-lunarg** [comment]
Validation supported added https://github.com/KhronosGroup/SPIRV-Tools/pull/6524 (in case someone searches)
