### ISSUE TITLE
Task list for VK_EXT_primitive_topology_list_restart release

### ISSUE THREAD

**Issue by ShabbyX** [KhronosGroup/Vulkan-Docs#1632]
This extension allows primitive restart (i.e. `VkPipelineInputAssemblyStateCreateInfo::primitiveRestartEnable`) with list primitive topologies. Similarly to OpenGL, this feature is optional for patch lists.

The task list for the VK_EXT_primitive_topology_list_restart release is:

 - [x] Vulkan Specification: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_primitive_topology_list_restart.html
 - [x] Conformance tests released: Added in [CTS 1.2.8.0](https://github.com/KhronosGroup/VK-GL-CTS/releases/tag/vulkan-cts-1.2.8.0): https://github.com/KhronosGroup/VK-GL-CTS/commit/a32da5acdec50e4c8a67c548a5f254f0ac65b871
 - [x] SDK released: [Vulkan SDK 1.2.198.0](https://vulkan.lunarg.com/sdk/home)
     - [x] Validation layer: https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/3236

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.
