### ISSUE TITLE
Task list for VK_EXT_rgba10x6_formats release 

### ISSUE THREAD

**Issue by janharaldfredriksen-arm** [KhronosGroup/Vulkan-Docs#1652]
Release Task List

This extension enables the VK_FORMAT_R10X6G10X6B10X6A10X6_UNORM_4PACK16 format to be used without a sampler Y′CBCR conversion enabled, and turns it into a "regular" image format that can be used for rendering and texturing, though no specific image usage flag bits are required to be supported by this extension.

The task list for the VK_EXT_rgba10x6_formats  release is:

 - [x] Vulkan Specification:  https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_rgba10x6_formats.html
 - [x] Conformance tests released: https://github.com/KhronosGroup/VK-GL-CTS/releases/tag/vulkan-cts-1.2.8.0
 - [x] SDK released: 1.2.198.0

     - [x] Validation layer: https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/3397

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.

**Comment by janharaldfredriksen-arm** [comment]
All done, closing.
