### ISSUE TITLE
Task list for VK_KHR_dynamic_rendering release 

### ISSUE THREAD

**Issue by Tobski** [KhronosGroup/Vulkan-Docs#1677]
This extension allows applications to create single-pass render pass instances without needing to create render pass objects or framebuffers. Dynamic render passes can also span across multiple primary command buffers, rather than relying on secondary command buffers.

This extension also incorporates VK_ATTACHMENT_STORE_OP_NONE_KHR from VK_QCOM_render_pass_store_ops, enabling applications to avoid unnecessary synchronization when an attachment is not written during a render pass.

The task list for the VK_KHR_dynamic_rendering release is:

 - [x] Vulkan Specification:  [Extension Man Page](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_dynamic_rendering.html)
 - [x] Conformance tests released: https://github.com/KhronosGroup/VK-GL-CTS/releases/tag/vulkan-cts-1.3.1.0
 - [x] SDK released: (target: April 18) 
 - [x] Validation Layer support
     - [x] Compatible validation: <https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/3517>
     - [x] Further validation: <https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/3946>
 - [x] Vulkan Guide:  [Proposal Doc](https://github.com/KhronosGroup/Vulkan-Docs/blob/main/proposals/VK_KHR_dynamic_rendering.asciidoc)
 - [x] API Examples:  KhronosGroup/Vulkan-Samples#394
 - [x] [Blog Post](https://www.khronos.org/blog/streamlining-render-passes)
 - [x] Drivers:
     - [x] NVIDIA Beta driver: https://developer.nvidia.com/vulkan-driver
     - [x] AMD Radeon Adrenaline driver: https://www.amd.com/en/support/kb/release-notes/rn-rad-win-21-11-3

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.

**Comment by pdaniell-nv** [comment]
The latest NVIDIA Beta driver supports this extension and can be found here: https://developer.nvidia.com/vulkan-driver

**Comment by Tobski** [comment]
An AMD driver supporting this extension should be available on the 18th of November; see here for details when that occurs: https://www.amd.com/en/support/kb/release-notes/rn-rad-win-vulkan

**Comment by SaschaWillems** [comment]
@gpx1000 is working on a dynamic rendering api samples for the Khronos sample repository, see https://github.com/KhronosGroup/Vulkan-Samples/pull/394

**Comment by Tobski** [comment]
> An AMD driver supporting this extension should be available on the 18th of November; see here for details when that occurs: https://www.amd.com/en/support/kb/release-notes/rn-rad-win-vulkan

For various reasons this driver release has unfortunately had to be pushed back by a few days but will be available soon; I'll update the tracker when it's available.

**Comment by Tobski** [comment]
Some confusion about when it went out, but the latest Radeon Adrenaline driver supports this extension, details here: https://www.amd.com/en/support/kb/release-notes/rn-rad-win-21-11-3

**Comment by Perksey** [comment]
Is the implementation of this by mobile vendors and/or Vulkan Portability Initiative vendors being tracked as well?

**Comment by gpx1000** [comment]
The sample KhronosGroup/Vulkan-Samples#394 has been merged; should be considered live.

**Comment by Tobski** [comment]
> Is the implementation of this by mobile vendors and/or Vulkan Portability Initiative vendors being tracked as well?

It's up to individual vendors to add their driver status, so no not at the moment. @dgkoch do you have any ideas about portability?

**Comment by dgkoch** [comment]
> @dgkoch do you have any ideas about portability?

No - that sounds like a question for @billhollings
