### ISSUE TITLE
Task list for VK_EXT_image_view_min_lod release

### ISSUE THREAD

**Issue by HansKristian-Work** [KhronosGroup/Vulkan-Docs#1689]
This extension allows setting a minimum LOD on VkImageView objects. This is intended to map directly to D3D11/12's SRV ResourceMinLOD parameter. The LOD clamp can be fractional and has some use cases in API translation as well as sparse texturing scenarios where LODs are dynamically paged in and out where it may be desirable to gradually introduce new mip levels. Essentially, this is a view object version of SPIR-V MinLod optional parameter.

The task list for the VK_EXT_image_view_min_lod release is:

 - [x] Vulkan Specification:  [Extension Man Page](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_image_view_min_lod.html)
 - [x] Conformance tests released: https://github.com/KhronosGroup/VK-GL-CTS/releases/tag/vulkan-cts-1.3.1.0
 - [x] SDK released: Version 1.3.204.0 (March 2022)
     - [x] Validation layer: [new VU support](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/3578)
 - [x] Vulkan Guide:  [Guide entry](https://github.com/KhronosGroup/Vulkan-Guide/blob/master/chapters/extensions/translation_layer_extensions.adoc#vk_ext_image_view_min_lod)
 - [ ] API Examples:  

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.
