### ISSUE TITLE
Task list for VK_EXT_depth_clip_control release

### ISSUE THREAD

**Issue by ShabbyX** [KhronosGroup/Vulkan-Docs#1710]
This extension allows the application to use the OpenGL depth range in NDC, i.e. with depth in range `[-1, 1]`, as opposed to Vulkan's default of `[0, 1]`. The purpose of this extension is purely to allow efficient layering of OpenGL over Vulkan, by avoiding emulation in the pre-rasterization shader stages. This emulation, which effectively duplicates gl_Position but with a different depth value, costs ALU and consumes shader output components that the implementation may not have to spare to meet OpenGL minimum requirements.

Use of this extension outside OpenGL emulation or porting OpenGL applications is **not** recommended.

The task list for the VK_EXT_depth_clip_control release is:

 - [x] Vulkan Specification:  https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_depth_clip_control.html
 - [x] Conformance tests released: https://github.com/KhronosGroup/VK-GL-CTS/releases/tag/vulkan-cts-1.3.1.0
 - [x] SDK released: [Vulkan SDK 1.3.204.0](https://vulkan.lunarg.com/sdk/home)
     - [x] Validation layer: https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/3577
 - [x] Vulkan Guide:  https://github.com/KhronosGroup/Vulkan-Guide/pull/151
 
As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.
