### ISSUE TITLE
Task list for Vulkan 1.3 release

### ISSUE THREAD

**Issue by Tobski** [KhronosGroup/Vulkan-Docs#1748]
Vulkan 1.3 incorporates a number of carefully selected extensions requested by the developer community into a new core version of the specification. These include dynamic rendering, additional dynamic state, an improved synchronization API, and a range of other features (see the Vulkan 1.3 and Roadmap blog post for details). Crucially, unlike previous revisions, no features added to Vulkan 1.3 are optional, ensuring their consistent availability in all implementations of this new API version.

Vulkan is an ecosystem-driven API; the Vulkan and SPIR-V Working Groups define the specification, but the tools developers need to use the API come many teams across the Vulkan community. This issue tracks the state of the various documents and software artifacts needed to develop Vulkan 1.3 applications. As each item is made public, the task will be checked off below. When all tasks have been checked off, this issue will be closed and the Vulkan 1.3 release will be complete.

The task list for the Vulkan 1.3 release is:
* [x] Vulkan specification: https://www.khronos.org/registry/vulkan/#apispecs
* [x] Vulkan headers: https://github.com/KhronosGroup/Vulkan-Headers
* [ ] SPIRV-Tools
* [ ] glslang support
* [ ] shaderc support
* [ ] DXC support
* [ ] Validation Layer support
* [ ] Loader support
* [ ] Tools support
* [ ] Vulkan 1.3 SDK
* [ ] Vulkan 1.3 Conformance Test Suite (CTS)

**Comment by krOoze** [comment]
The link in the blog pointing to The Roadmap is dead.

**Comment by Tobski** [comment]
> The link in the blog pointing to The Roadmap is dead. (Points to `#_roadmap_2022` which does not exist in the spec).

Thanks for spotting this - should be pointing here: https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#roadmap-2022

**Comment by malnasse** [comment]
Vulkan beta drivers for AMD which are expected to pass the Khronos Conformance Process are available at https://www.amd.com/en/support/kb/release-notes/rn-rad-win-22-1-2-vulkan-1-3. Current conformance status can be found at www.khronos.org/conformance.”

**Comment by oscarbg** [comment]
on the conformance status site, it’s showed Intel has Vulkan 1.3 Windows drivers passing CTS.. hope some Intel dev posts here some link to a public beta/production 1.3 driver as soon as is posted online.

**Comment by TomOlson** [comment]
SDK is now available so the tasks are complete. Note the SDK [webinar](https://www.khronos.org/events/a-vulkanised-webinar-march-2022) later this week - you can attend live or catch recordings at https://youtube.com/vulkan later. We'll close this issue after the event.
