### ISSUE TITLE
Task list for VK_KHR_portability_enumeration release

### ISSUE THREAD

**Issue by charles-lunarg** [KhronosGroup/Vulkan-Docs#1802]
This extension allows applications to control whether devices that expose the [VK_KHR_portability_subset](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_KHR_portability_subset.html) extension are included in the results of physical device enumeration. Since devices which support the [VK_KHR_portability_subset](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_KHR_portability_subset.html) extension are not fully conformant Vulkan implementations, the Vulkan loader does not report those devices unless the application explicitly asks for them. This prevents applications which may not be aware of non-conformant devices from accidentally using them, as any device which supports the [VK_KHR_portability_subset](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_KHR_portability_subset.html) extension mandates that the extension must be enabled if that device is used.

The task list for the VK_KHR_dynamic_rendering release is:

 - [x] Vulkan Specification:  [Extension Man Page](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_KHR_portability_enumeration.html)

 - [x] Conformance tests released: [release notes](https://github.com/KhronosGroup/VK-GL-CTS/releases/tag/vulkan-cts-1.3.3.0)

 - [x] Vulkan Loader phase I support (Target of mid April): Issue warning if user is using MoltenVK implementation without first requesting exposure of that implementation via the enumeration extension)

 - [x] Vulkan Loader phase II support (Target of June): Remove warning; no longer return portability implementations unless explicitly requested by use of the enumeration extension)

 - [x] SDK released (Phase 1): SDK 1.3.211.0
 - [x] SDK released (Phase 2): SDK 1.3.216.0

 - [x] API Examples:  https://github.com/KhronosGroup/Vulkan-Samples/tree/master/samples/extensions/portability

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.

**Comment by krOoze** [comment]
Could it go ahead and also add something like `VK_INSTANCE_CREATE_ENUMERATE_BETA_BIT_KHR` to replace the attrocious ill-adviced practice of printing to console:

> WARNING: XXX is not a conformant vulkan implementation, testing use only.

Unfortunately there're probably no reasonable ways to retrospectively blacklist those drivers except perhaps detect this message in the loader somehow...

**Comment by marty-johnson59** [comment]
All planned tasks are now complete - closing
