### ISSUE TITLE
Task list for VK_EXT_graphics_pipeline_library 

### ISSUE THREAD

**Issue by Tobski** [KhronosGroup/Vulkan-Docs#1808]
This extension allows partial compilation of portions of pipelines, improving the performance of pipeline compilation for applications that have large numbers of materials, large amounts of dynamic state, or continuously stream in new material definitions.

The task list for the VK_EXT_graphics_pipeline_library release is:

 - [ ] Vulkan Specification: <[VK_EXT_graphics_pipeline_library appendix](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_EXT_graphics_pipeline_library.html)>
 - [ ] [Proposal](https://github.com/KhronosGroup/Vulkan-Docs/blob/main/proposals/VK_EXT_graphics_pipeline_library.asciidoc)
 - [ ] Conformance tests released: 
 - [ ] SDK released: 

     - [ ] Validation layer: 
     - [ ] Emulation layer: 

 - [ ] API Examples:  

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.

**Comment by SaschaWillems** [comment]
I'd be willing to do an api sample for our Khronos Samples repo.

**Comment by KarenGhavam-lunarG** [comment]
@Tobski What is the emulation layer in the checklist?

**Comment by Tobski** [comment]
> @Tobski What is the emulation layer in the checklist?

Err, an accident is what it is.

I think this is desired but we haven't resourced it yet, and shouldn't be gating release completion on it at this time.
