### ISSUE TITLE
Task list for VK_EXT_primitives_generated_query

### ISSUE THREAD

**Issue by ShabbyX** [KhronosGroup/Vulkan-Docs#1812]
In OpenGL, the `GL_PRIMITIVES_GENERATED` query can be used independently from whether transform feedback is active or not. There is no direct equivalent in Vulkan. This extension provides a simple and efficient way to implement this OpenGL query on top of Vulkan.

Use of this extension outside OpenGL emulation or porting OpenGL applications is **not** recommended.

The task list for the VK_EXT_primitives_generated_query release is:

 - [x] Vulkan Specification:  https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_EXT_primitives_generated_query.html
 - [x] Conformance tests released: https://github.com/KhronosGroup/VK-GL-CTS/releases/tag/vulkan-cts-1.3.2.0
 - [x] SDK released: [Vulkan SDK 1.3.216.0](https://vulkan.lunarg.com/sdk/home)
   - [x] Validation layer: (PRs: https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4010, https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4016)
 
As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.

**Comment by ShabbyX** [comment]
@Tony-LunarG it doesn't look like SDK 1.3.211.0 has support for this extension, isn't that correct? Why is it checked off?

**Comment by Tony-LunarG** [comment]
As noted in https://gitlab.khronos.org/vulkan/vulkan-operations/-/issues/149, the validation is in the repo but missed the SDK release
