### ISSUE TITLE
Task list for VK_EXT_image_2d_view_of_3d release

### ISSUE THREAD

**Issue by zmike** [KhronosGroup/Vulkan-Docs#1820]
This extension is used to emulate GL functionality, allowing the use of a single 3D image slice in sampling and storage shader operations.

The task list for the VK_EXT_image_2d_view_of_3d release is:

 - [x] Vulkan Specification:  https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_EXT_image_2d_view_of_3d.html
 - [x] Conformance tests released: 
 - [x] SDK released: Version 1.3.211.0 (April 2022)
     - [x] Validation layer: 

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.
