### ISSUE TITLE
Task list for VK_KHR_ray_tracing_maintenance1 release

### ISSUE THREAD

**Issue by dgkoch** [KhronosGroup/Vulkan-Docs#1847]
Release Task List

VK_KHR_ray_tracing_maintenance1 adds a collection of minor ray tracing features, none of which would warrant an entire extension of their own.

The new features are as follows:

- Adds support for the SPV_KHR_ray_cull_mask SPIR-V extension in Vulkan. This extension provides access to built-in CullMaskKHR shader variable which contains the value of the OpTrace* Cull Mask parameter. This new shader variable is accessible in the intersection, any-hit, closest-hit and miss shader stages.
- Adds support for a new pipeline stage and access mask built on top of [VK_KHR_synchronization2](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VK_KHR_synchronization2):
  - VK_PIPELINE_STAGE_2_ACCELERATION_STRUCTURE_COPY_BIT_KHR to specify execution of [acceleration structure copy commands](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#acceleration-structure-copying)
  - VK_ACCESS_2_SHADER_BINDING_TABLE_READ_BIT_KHR to specify read access to a [shader binding table](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#shader-binding-table) in any shader pipeline stage
- Adds two new acceleration structure query parameters:
  - VK_QUERY_TYPE_ACCELERATION_STRUCTURE_SIZE_KHR to query the acceleration structure size on the device timeline
  - VK_QUERY_TYPE_ACCELERATION_STRUCTURE_SERIALIZATION_BOTTOM_LEVEL_POINTERS_KHR to query the number of bottom level acceleration structure pointers for serialization
- Adds an optional new indirect ray tracing dispatch command, [vkCmdTraceRaysIndirect2KHR](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#vkCmdTraceRaysIndirect2KHR), which sources the shader binding table parameters as well as the dispatch dimensions from the device. The [rayTracingPipelineTraceRaysIndirect2](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#features-rayTracingPipelineTraceRaysIndirect2) feature indicates whether this functionality is supported.

The task list for the VK_KHR_ray_tracing_maintenance1 release is:

 - [x] Vulkan Specification:  [VK_KHR_ray_tracing_maintenance1](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VK_KHR_ray_tracing_maintenance1)
 - [x] SPIRV specification:  [Add SPV_KHR_ray_cull_mask](https://github.com/KhronosGroup/SPIRV-Registry/pull/142)
 - [x] SPIRV Headers:  [Add SPV_KHR_ray_cull_mask](https://github.com/KhronosGroup/SPIRV-Headers/pull/279)
 - [x] SPIRV tools released: [spirv-val: Add CullMaskKHR support](https://github.com/KhronosGroup/SPIRV-Tools/pull/4792)
 - [x] GLSL extension: [Add GL_EXT_ray_cull_mask](https://github.com/KhronosGroup/GLSL/pull/179)
 - [x] Glslang implementation: [Adding support for GL_EXT_ray_cull_mask](https://github.com/KhronosGroup/glslang/pull/2938)
 - Validation
   - [x] basic validation support: [layers: Add VK_KHR_ray_tracing_maintenance1](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4112)
   - [ ] more validation support [Add missing VUIDs from VK_KHR_ray_tracing_maintenance1](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4120)
 - [x] Conformance tests released: VK 1.3.3.0 CTS includes support
 - [x] SDK released: 1.3.216 SDK

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.

**Comment by dgkoch** [comment]
Added validation support link: https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4112

**Comment by dgkoch** [comment]
support released in 1.3.216 SDK

**Comment by dgkoch** [comment]
CTS support was released in VK 1.3.3.0 CTS.
