### ISSUE TITLE
Task list for VK_KHR_fragment_shader_barycentric release

### ISSUE THREAD

**Issue by stu-s** [KhronosGroup/Vulkan-Docs#1863]
Release Task List

This extension is based on the VK_NV_fragment_shader_barycentric extension, and adds support for
the following SPIR-V extension in Vulkan:
- SPV_KHR_fragment_shader_barycentric

The extension provides access to three additional fragment shader variable decorations in SPIR-V:
- PerVertexKHR, which indicates that a fragment shader input will not have interpolated values,
but instead must be accessed with an extra array index that identifies one of the vertices of the
primitive producing the fragment
- BaryCoordKHR, which indicates that the variable is a three-component floating-point vector
holding barycentric weights for the fragment produced using perspective interpolation
- BaryCoordNoPerspKHR, which indicates that the variable is a three-component floating-point
vector holding barycentric weights for the fragment produced using linear interpolation

When using GLSL source-based shader languages, the following variables from
GL_EXT_fragment_shader_barycentric map to these SPIR-V built-in decorations:
- in vec3 gl_BaryCoordEXT; → BaryCoordKHR
- in vec3 gl_BaryCoordNoPerspEXT; → BaryCoordNoPerspKHR

GLSL variables declared using the pervertexEXT GLSL qualifier are expected to be decorated with
PerVertexKHR in SPIR-V.

The task list for the  release is:

 - [x] Vulkan Specification:  https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VK_KHR_fragment_shader_barycentric
 - [x] SPIRV specification:  https://github.com/KhronosGroup/SPIRV-Registry/pull/146
 - [x] SPIRV Headers:  merged
 - [x] SPIRV tools released: https://github.com/KhronosGroup/SPIRV-Tools/pull/4805
 - [x] GLSL extension: https://github.com/KhronosGroup/GLSL/pull/183
 - [x] Glslang implementation: https://github.com/KhronosGroup/glslang/pull/2952
 - [x] Conformance tests released: 
 - [x] Validation - covered in SPIRV tools
 - [x] SDK released: SDK 1.3.216.0 released on June 14
 - [x] HLSL DXC support: https://github.com/microsoft/DirectXShaderCompiler/pull/4638 https://github.com/microsoft/DirectXShaderCompiler/pull/4638

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.

**Comment by pdaniell-nv** [comment]
Driver support for NVIDIA GTX 1650+ and NVIDIA RTX 2060+ (Turing) GPUs is available here: https://developer.nvidia.com/vulkan-driver

**Comment by martty** [comment]
Are there future plans to extend coverage of this extension to the still supported range of NV cards (Maxwell, Pascal) to match DX12 SV_Barycentrics support?

**Comment by pdaniell-nv** [comment]
> Are there future plans to extend coverage of this extension to the still supported range of NV cards (Maxwell, Pascal) to match DX12 SV_Barycentrics support?

No plans to support it with GPUs prior to Turing on Vulkan since they lack the necessary hardware support. It's a surprise to me to hear that SV_Barycentrics is supported on Pascal and Maxwell.

**Comment by pdaniell-nv** [comment]
> > Are there future plans to extend coverage of this extension to the still supported range of NV cards (Maxwell, Pascal) to match DX12 SV_Barycentrics support?
> 
> No plans to support it with GPUs prior to Turing on Vulkan since they lack the necessary hardware support. It's a surprise to me to hear that SV_Barycentrics is supported on Pascal and Maxwell.

I think you'll find if you query [D3D12_FEATURE_DATA_D3D12_OPTIONS3](https://docs.microsoft.com/en-us/windows/win32/api/d3d12/ns-d3d12-d3d12_feature_data_d3d12_options3) on Pascal and Maxwell that BarycentricsSupported=FALSE.

**Comment by martty** [comment]
Thank you for the clarification! Apologies, I was under the assumption that this was a mandatory thing in DX12 land..
