### ISSUE TITLE
Task list for VK_EXT_multisampled_render_to_single_sampled

### ISSUE THREAD

**Issue by ShabbyX** [KhronosGroup/Vulkan-Docs#1897]
With careful usage of resolve attachments, multisampled image memory allocated with `VK_MEMORY_PROPERTY_LAZILY_ALLOCATED_BIT`, `loadOp` not equal to `VK_ATTACHMENT_LOAD_OP_LOAD`, and `storeOp` not equal to `VK_ATTACHMENT_STORE_OP_STORE`, a Vulkan application is able to efficiently perform multisampled rendering without incurring any additional memory penalty on tiling GPUs in most cases.

However, under certain circumstances, the application may not be able to complete its multisampled rendering within a single render pass; for example if it does partial rasterization from frame to frame, blending on an image from a previous frame, or in emulation of `GL_EXT_multisampled_render_to_texture`. In such cases, the application can use an initial subpass to effectively load single sampled data from the next subpass's resolve attachment and fill in the multisampled attachment which otherwise uses `loadOp` equal to `VK_ATTACHMENT_LOAD_OP_DONT_CARE`. However, this is not always possible (for example for stencil in the absence of `VK_EXT_shader_stencil_export`) and has multiple drawbacks.

Some implementations are able to perform said operation efficiently in hardware, effectively loading a multisampled attachment from the contents of a single sampled one. Together with the ability to perform a resolve operation at the end of a subpass, these implementations are able to perform multisampled rendering on single-sampled attachments with no extra memory or bandwidth overhead.

This extension exposes said hardware feature by allowing single-sampled attachments to participate in a multisampled render pass. For these attachments, the implementation would implicitly render to an implicit multisampled image, typically not one that is actually allocated from VRAM, but rather exists solely on the GPU's tile memory. This implicit image is initialized from the single-sampled attachment, if load op is `VK_ATTACHMENT_LOAD_OP_LOAD`, and is automatically resolved to the single-sampled attachment at the end of the render pass, if store op is `VK_ATTACHMENT_STORE_OP_STORE`.

The task list for the VK_EXT_multisampled_render_to_single_sampled release is:

 - [x] Vulkan Specification: https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_EXT_multisampled_render_to_single_sampled.html
 - [x] Conformance tests released: https://github.com/KhronosGroup/VK-GL-CTS/releases/tag/vulkan-cts-1.3.4.0
 - [x] SDK released: [Vulkan SDK 1.3.224.1](https://vulkan.lunarg.com/sdk/home)
     - [x] Validation layer: https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4367

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.
