### ISSUE TITLE
Task list for VK_EXT_mesh_shader release

### ISSUE THREAD

**Issue by pdaniell-nv** [KhronosGroup/Vulkan-Docs#1927]
Release Task List

Multi-vendor mesh shading for Vulkan. This extension provides a new mechanism allowing applications to generate collections of geometric primitives via programmable mesh shading. It is an alternative to the existing programmable primitive shading pipeline, which relied on generating input primitives by a fixed function assembler as well as fixed function vertex fetch.

The task list for the VK_EXT_mesh_shader release is:

 - [x] Vulkan Specification: https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VK_EXT_mesh_shader
 - [ ] SPIRV specification:  
 - [ ] SPIRV Headers:  
 - [ ] SPIRV tools released: 
 - [ ] GLSL extension: 
 - [ ] Glslang implementation: 
 - [ ] Conformance tests released: 
 - [ ] SDK released: 

     - [ ] Validation layer: 
     - [ ] Emulation layer: 

 - [ ] Vulkan Guide:  
 - [ ] API Examples:  
 - [ ] Shaderc:  
 - [ ] HLSL mapping:
 - [ ] HLSL glslang support:
 - [ ] HLSL DXC support: 

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.

**Comment by pdaniell-nv** [comment]
Beta drivers for NVIDIA GPUs are available here: https://developer.nvidia.com/vulkan-driver

**Comment by dgkoch** [comment]
https://github.com/KhronosGroup/SPIRV-Headers/pull/288

**Comment by dgkoch** [comment]
- https://github.com/google/shaderc/pull/1264
- https://github.com/KhronosGroup/glslang/pull/3014
- https://github.com/KhronosGroup/SPIRV-Tools/pull/4915

**Comment by zeux** [comment]
Not an official example by any means but https://github.com/zeux/niagara was updated to EXT_mesh_shader (see https://github.com/zeux/niagara/pull/27), tested on latest radv.

**Comment by BeastLe9enD** [comment]
There is a PR for HLSL support in DXC: https://github.com/microsoft/DirectXShaderCompiler/pull/4725 :)

**Comment by KlingelingelingDerEiermann** [comment]
Unfortunately there is currently no debugger x(
In case anyone from Khronos is listening:
If I were you, I would financially support RenderDoc to support the feature. It's being developed by one person right now, and you really can't ask them to do it on their spare time.
https://github.com/baldurk/renderdoc/issues/2743

**Comment by Andreyogld3d** [comment]
What about  HLSL DXC support ?
I could compiled shaders from [Direct3D12 Mesh Shader cull sample](https://github.com/microsoft/DirectX-Graphics-Samples/tree/master/Samples/Desktop/D3D12MeshShaders/src/MeshletCull)(
[MeshletAS.hlsl](https://github.com/microsoft/DirectX-Graphics-Samples/blob/master/Samples/Desktop/D3D12MeshShaders/src/MeshletCull/MeshletAS.hlsl),
[MeshletMS.hlsl](https://github.com/microsoft/DirectX-Graphics-Samples/blob/master/Samples/Desktop/D3D12MeshShaders/src/MeshletCull/MeshletMS.hlsl))
and use them for Vulkan's test demo

**Comment by BeastLe9enD** [comment]
@Andreyogld3d DXC supports HLSL mesh shaders with VK_EXT_mesh_shader. See https://github.com/microsoft/DirectXShaderCompiler/pull/4725

**Comment by Andreyogld3d** [comment]
@BeastLe9enD, so in this case we can we check off task "DXC HLSL support"?

**Comment by BeastLe9enD** [comment]
@Andreyogld3d I think so! I worked with HLSL mesh shaders with the decompiler shipped with the new Vulkan SDK and I had no problems!

**Comment by Andreyogld3d** [comment]
@pdaniell-nv 
we can check off task "DXC HLSL support" https://github.com/microsoft/DirectXShaderCompiler/pull/4725
