### ISSUE TITLE
Task List for VK_EXT_depth_clamp_zero_one release

### ISSUE THREAD

**Issue by gnl21** [KhronosGroup/Vulkan-Docs#1929]
Release Task List

Implementations had inconsistent behavior when depth values fell outside the viewport depth range and the resulting depth value was therefore undefined. In order to ensure consistent behavior in the future, this extension defines the preferred outcome.

The task list for the VK_EXT_depth_clamp_zero_one release is:

 - [x] Vulkan Specification:  [VK_EXT_depth_clamp_zero_one](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#VK_EXT_depth_clamp_zero_one)
 - [x] Conformance tests released: [v1.3.4.0](https://github.com/KhronosGroup/VK-GL-CTS/releases/tag/vulkan-cts-1.3.4.0)
 - [x] SDK released: [sdk-1.3.231.0](https://vulkan.lunarg.com/sdk/home)

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.
