### ISSUE TITLE
Task list for VK_EXT_legacy_dithering

### ISSUE THREAD

**Issue by ShabbyX** [KhronosGroup/Vulkan-Docs#1939]
Some hardware include features to implement OpenGL's dithering. Dithering is best implemented by the Vulkan application. However, some OpenGL applications have come to (accidentally or not) rely on OpenGL's by-default-on dithering, especially on Android. For OpenGL layer implementations, this extension exposes said hardware feature for efficient dithering.

**Note**: This extension provides no guarantees that dithering is actually done on any format. The intended use is to get dithering equivalent to the vendor's OpenGL implementation, regardless of whether it's applied at all, or if it's applied correctly.

**Do not use outside of an OpenGL emulation layer.**

The task list for the VK_EXT_legacy_dithering release is:

 - [x] Vulkan Specification: https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_EXT_legacy_dithering.html
 - [x] Conformance tests released: https://github.com/KhronosGroup/VK-GL-CTS/releases/tag/vulkan-cts-1.3.5.0
 - [x] SDK released: Extension included in SDK 1.3.231.1 release October 26, 2022
     - [x] Validation layer: https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4532

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.
