### ISSUE TITLE
Task list for VK_EXT_opacity_micromap

### ISSUE THREAD

**Issue by dgkoch** [KhronosGroup/Vulkan-Docs#1960]
Release Task List

When adding adding transparency to a ray traced scene, an application can choose between further tessellating the geometry or using an any hit shader to allow the ray through specific parts of the geometry. These options have the downside of either significantly increasing memory consumption or adding runtime overhead to run shader code in the middle of traversal, respectively.

This extension adds the ability to add an opacity micromap to geometry when building an acceleration structure. The opacity micromap compactly encodes opacity information which can be read by the implementation to mark parts of triangles as opaque or transparent. The format is externally visible to allow the application to compress its internal geometry and surface representations into the compressed format ahead of time. The compressed format subdivides each triangle into a set of subtriangles, each of which can be assigned either two or four opacity values. These opacity values can control if a ray hitting that subtriangle is treated as an opaque hit, complete miss, or possible hit, depending on the controls described in [Ray Opacity Micromap](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#ray-opacity-micromap).

The task list for the  release is:
 - [x] Vulkan Specification:  [VK_EXT_opacity_micropmap](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#VK_EXT_opacity_micromap)
 - [x] SPIRV specification:  https://github.com/KhronosGroup/SPIRV-Registry/pull/171
 - [x] SPIRV Headers:  
    - https://github.com/KhronosGroup/SPIRV-Headers/pull/292
    - https://github.com/KhronosGroup/SPIRV-Headers/pull/295
 - [x] SPIRV tools released: No changes needed - just needs a DEPS update once SPIRV-Headers lands 
 - [x] GLSL extension: https://github.com/KhronosGroup/GLSL/pull/191
 - [x] Glslang implementation: https://github.com/KhronosGroup/glslang/pull/3038
 - [x] Conformance tests released: Vulkan CTS 1.3.5.0
 - [ ] SDK released: 
     - [x] Validation layer: https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4607 (non-functional as posted because validation updates can't sequence with dependency updates)
 - [ ] Shaderc:  

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.
