### ISSUE TITLE
Task list for VK_EXT_extended_dynamic_state3

### ISSUE THREAD

**Issue by pdaniell-nv** [KhronosGroup/Vulkan-Docs#1961]
Release Task List

Title of issue:  Task list for VK_EXT_extended_dynamic_state3 release

This extension adds several more dynamic states, which together with existing Vulkan 1.3 dynamic state, should cover almost all remaining pipeline state. All dynamic state is optional to allow implementations to support whatever they can today, and incrementally add more in future.

The task list for the VK_EXT_extended_dynamic_state3 release is:

 - [x] Vulkan Specification: [VK_EXT_extended_dynamic_state3](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_EXT_extended_dynamic_state3.html)
 - [x] Conformance tests released: [vulkan-cts-1.3.5.0](https://github.com/KhronosGroup/VK-GL-CTS/releases/tag/vulkan-cts-1.3.5.0)
 - [x] SDK released: Version 1.3.231.0 (October 2022)
     - [x] Validation layer: (https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4632)

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.
