### ISSUE TITLE
Task list for VK_EXT_pipeline_protected_access

### ISSUE THREAD

**Issue by ShabbyX** [KhronosGroup/Vulkan-Docs#1969]
On some implementations, knowledge of whether a pipeline cannot or can only be used in a protected command buffer can result in more efficient compilation or even runtime performance. This extension adds two flags to exactly specify that.

The task list for the VK_EXT_pipeline_protected_access release is:

 - [x] Vulkan Specification: https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_EXT_pipeline_protected_access.html
 - [x] Conformance tests released: https://github.com/KhronosGroup/VK-GL-CTS/releases/tag/vulkan-cts-1.3.5.0
 - [x] SDK released: Extension included in SDK 1.3.231.1 release October 26, 2022
     - [x] Validation layer: https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4648

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.
