### ISSUE TITLE
Task list of VK_NV_ray_tracing_invocation_reorder

### ISSUE THREAD

**Issue by alelenv** [KhronosGroup/Vulkan-Docs#1972]
Release Task List

Task list for VK_NV_ray_tracing_invocation_reorder release

The task list for the  release is:

 - [x] Vulkan Specification:  https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#VK_NV_ray_tracing_invocation_reorder
 - [x] SPIRV specification:  https://github.com/KhronosGroup/SPIRV-Registry/pull/175
 - [x] SPIRV Headers:  https://github.com/KhronosGroup/SPIRV-Headers/pull/300
 - [x] SPIRV tools released: https://github.com/KhronosGroup/SPIRV-Tools/pull/4979
 - [x] GLSL extension: https://github.com/KhronosGroup/GLSL/pull/196
 - [x] Glslang implementation: https://github.com/KhronosGroup/glslang/pull/3054

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.

**Comment by alelenv** [comment]
All items are done. Should be okay to close

**Comment by Clothoid1** [comment]
Should't HLSL support with DXC not also be in this task list?
