### ISSUE TITLE
Task list for VK_EXT_descriptor_buffer release

### ISSUE THREAD

**Issue by stu-s** [KhronosGroup/Vulkan-Docs#1990]
This extension introduces new commands to put shader-accessible descriptors directly in memory, making the management of descriptor data more explicit.

 - [x] Vulkan Specification:  [VK_EXT_descriptor_buffer](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_EXT_descriptor_buffer.html)
 - [x] Conformance tests released: 
 - [x] SDK released: Version 1.3.236.0
     - [x] Validation layer: https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4828
 - [x] Drivers:
     - [x] RADV: https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/19808
     - [x] AMD: https://www.amd.com/en/support/kb/release-notes/rn-rad-win-22-11-1-vlk
     - [x] NV: https://developer.nvidia.com/vulkan-driver
 - [x] Blog: https://www.khronos.org/blog/vk-ext-descriptor-buffer

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.

**Comment by HansKristian-Work** [comment]
- RADV MR: https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/19808
- Application in the wild: vkd3d-proton: https://github.com/HansKristian-Work/vkd3d-proton/pull/1297

**Comment by Tobski** [comment]
AMD Windows KB driver supporting this is now available: https://www.amd.com/en/support/kb/release-notes/rn-rad-win-22-11-1-vlk

**Comment by pdaniell-nv** [comment]
The latest NVIDIA Vulkan Beta drivers now support this extension: https://developer.nvidia.com/vulkan-driver

**Comment by stu-s** [comment]
All tasks marked as done.  Closing.
