### ISSUE TITLE
Task list for VK_EXT_surface_maintenance1 and VK_EXT_swapchain_maintenance1 release

### ISSUE THREAD

**Issue by ShabbyX** [KhronosGroup/Vulkan-Docs#2006]
These extensions resolve a number of long-standing issues with Vulkan's WSI extensions. It is now possible to:

- Know when resources associated with a present operation can be destroyed
- Release acquired images back to swapchain without presenting them
- Specify scaling when creating the swapchain
- Defer swapchain memory allocation to acquire
- Switch present modes without recreating the swapchain

The task list for the VK_EXT_surface_maintenance1 and VK_EXT_swapchain_maintenance1 release is:

 - [x] Vulkan Specification:  https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_EXT_surface_maintenance1.html and https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_EXT_swapchain_maintenance1.html
 - [x] Conformance tests released: https://github.com/KhronosGroup/VK-GL-CTS/releases/tag/vulkan-cts-1.3.6.0
 - [x] SDK released: [Vulkan SDK 1.3.239.0](https://vulkan.lunarg.com/sdk/home)
     - [x] Validation layer: https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/5000

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.

**Comment by mark-lunarg** [comment]
Validation is under review [in this PR.](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/5000).  ETA is  <= 1/13/23.
