### ISSUE TITLE
Task list for VK_KHR_video_queue, VK_KHR_video_decode_queue, VK_KHR_video_decode_h264, and VK_KHR_video_decode_h265

### ISSUE THREAD

**Issue by aqnuep** [KhronosGroup/Vulkan-Docs#2014]
These extensions add support for the following Vulkan Video features:

- VK_KHR_video_queue - general video coding support
- VK_KHR_video_decode_queue - general video decode support
- VK_KHR_video_decode_h264 - H.264/AVC video decode support
- VK_KHR_video_decode_h265 - H.265/HEVC video decode support

The task list for the VK_KHR_video_queue, VK_KHR_video_decode_queue, VK_KHR_video_decode_h264, and VK_KHR_video_decode_h265 release is:

 - [x] Vulkan Specification:
     - [VK_KHR_video_queue](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_KHR_video_queue.html)
     - [VK_KHR_video_decode_queue](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_KHR_video_decode_queue.html)
     - [VK_KHR_video_decode_h264](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_KHR_video_decode_h264.html)
     - [VK_KHR_video_decode_h265](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_KHR_video_decode_h265.html)
 - [x] Conformance tests released: Vulkan CTS 1.3.5.0
 - [x] SDK released: Version 1.3.239.0
     - [x] Validation layer: https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4975
 - [x] [Blog Post](https://www.khronos.org/blog/khronos-finalizes-vulkan-video-extensions-for-accelerated-h.264-and-h.265-decode)
 - [x] Drivers:
     - NVIDIA Beta driver: [Windows and Linux](https://developer.nvidia.com/vulkan-driver)
     - Intel driver: coming soon
     - AMD Beta driver: [Windows](https://www.amd.com/en/support/kb/release-notes/rn-rad-win-vulkan)

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.

**Comment by pdaniell-nv** [comment]
NVIDIA public beta drivers can be found here: https://developer.nvidia.com/vulkan-driver

**Comment by Conan-Kudo** [comment]
I'm incredibly disappointed that AV1 support wasn't prioritized, given that AV1 is now supported by AMD, Intel, and NVIDIA GPUs now. It made sense several years ago to not prioritize it, but in the past year, it became pretty obvious that AV1 support is necessary.

For people who want to use royalty-free codecs, Vulkan Video is useless, potentially for _years_.

**Comment by aabdelkh** [comment]
VP9 decode and AV1 decode/encode are definitely on our list for 2023.  With the core extensions in place, releasing these should be a lot quicker.  We apologize for the delay!

**Comment by Conan-Kudo** [comment]
What sucks now is that vendors can claim Vulkan Video support without supporting a single royalty free codec. That's a massive disappointment.

**Comment by Conan-Kudo** [comment]
> VP9 decode

VP9 encoding should also be on the table: Intel has supported it since 2016, and many ARM SoCs support it too. It is unfortunate that AMD and NVIDIA don't have it, but that isn't a good enough reason to exclude everyone else from benefiting from it being specified.

**Comment by aabdelkh** [comment]
> VP9 encoding should also be on the table: Intel has supported it since 2016, and many ARM SoCs support it too. It is unfortunate that AMD and NVIDIA don't have it, but that isn't a good enough reason to exclude everyone else from benefiting from it being specified.

We're happy to specify an extension for VP9 encode as well, but we need participation from at least 2 IHVs implementing the extension.  Otherwise one IHV (e.g. Intel) may go ahead and define it as a vendor extension, and then it may be adopted (perhaps with just minor updates) to a EXT/KHR extension once an additional IHV supports it.

**Comment by aqnuep** [comment]
All tasks marked as done. Closing.

**Comment by Conan-Kudo** [comment]
> > VP9 encoding should also be on the table: Intel has supported it since 2016, and many ARM SoCs support it too. It is unfortunate that AMD and NVIDIA don't have it, but that isn't a good enough reason to exclude everyone else from benefiting from it being specified.
> 
> We're happy to specify an extension for VP9 encode as well, but we need participation from at least 2 IHVs implementing the extension. Otherwise one IHV (e.g. Intel) may go ahead and define it as a vendor extension, and then it may be adopted (perhaps with just minor updates) to become a EXT/KHR extension once an additional IHV supports it.

Last I checked, Arm; MediaTek; Qualcomm; and Samsung all have SoCs that support VP9 encoding. So Intel + any of these would count. It would shock me if Google _didn't_ want their ChromeOS/Android IHV partners to have this supported, particularly for WebRTC purposes.

**Comment by Conan-Kudo** [comment]
Well, color me shocked I guess. 🤯

**Comment by biendevera** [comment]
> These extensions add support for the following Vulkan Video features:
> 
> * VK_KHR_video_queue - general video coding support
> * VK_KHR_video_decode_queue - general video decode support
> * VK_KHR_video_decode_h264 - H.264/AVC video decode support
> * VK_KHR_video_decode_h265 - H.265/HEVC video decode support
> 
> The task list for the VK_KHR_video_queue, VK_KHR_video_decode_queue, VK_KHR_video_decode_h264, and VK_KHR_video_decode_h265 release is:
> 
> * [x]  Vulkan Specification:
>   
>   * [VK_KHR_video_queue](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_KHR_video_queue.html)
>   * [VK_KHR_video_decode_queue](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_KHR_video_decode_queue.html)
>   * [VK_KHR_video_decode_h264](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_KHR_video_decode_h264.html)
>   * [VK_KHR_video_decode_h265](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_KHR_video_decode_h265.html)
> * [x]  Conformance tests released: Vulkan CTS 1.3.5.0
> * [x]  SDK released: Version 1.3.239.0
>   
>   * [x]  Validation layer: [layers: Add support for video core and decode extensions Vulkan-ValidationLayers#4975](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4975)
> * [x]  [Blog Post](https://www.khronos.org/blog/khronos-finalizes-vulkan-video-extensions-for-accelerated-h.264-and-h.265-decode)
> * [x]  Drivers:
>   
>   * NVIDIA Beta driver: [Windows and Linux](https://developer.nvidia.com/vulkan-driver)
>   * Intel driver: coming soon
>   * AMD Beta driver: [Windows](https://www.amd.com/en/support/kb/release-notes/rn-rad-win-vulkan)
> 
> As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.
