### ISSUE TITLE
Task list for VK_KHR_ray_tracing_position_fetch

### ISSUE THREAD

**Issue by dgkoch** [KhronosGroup/Vulkan-Docs#2115]
Release Task List for VK_KHR_ray_tracing_position_fetch

Acceleration structures used in ray tracing have the position of the geometry provided to them at acceleration structure build time and need to have at least some derived form of the position encoded in them for ray tracing and queries. Applications frequently need to know the position or derived attribute of the triangle on a hit, so it is desirable to be able to retrieve that information to avoid duplication. One of the derived attributes that is of particular interest is the normal of the hit.

The task list for the VK_KHR_ray_tracing_position_fetch release is:

 - [x] Vulkan Specification:  [VK_KHR_ray_tracing_position_fetch](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#VK_KHR_ray_tracing_position_fetch)
 - [x] SPIRV specification:  [SPV_KHR_ray_tracing_position_fetch](https://htmlpreview.github.io/?https://github.com/KhronosGroup/SPIRV-Registry/blob/master/extensions/KHR/SPV_KHR_ray_tracing_position_fetch.html)
 - [x] SPIRV Headers:  https://github.com/KhronosGroup/SPIRV-Headers/pull/344
 - [x] SPIRV tools released: https://github.com/KhronosGroup/SPIRV-Tools/pull/5205
 - [x] GLSL extension: [GLSL_EXT_ray_tracing_position_fetch](https://github.com/KhronosGroup/GLSL/blob/master/extensions/ext/GLSL_EXT_ray_tracing_position_fetch.txt)
 - [x] Glslang implementation: https://github.com/KhronosGroup/glslang/pull/3201
 - [x] Conformance tests released: [1.3.7.0](https://github.com/KhronosGroup/VK-GL-CTS/releases/tag/vulkan-cts-1.3.7.0)
 - [x] SDK released: (maybe in 1.3.250.1; definitely in 1.3.261.1) 
 - [x] HLSL mapping: [SPIRV intrinsics only](https://github.com/KhronosGroup/Vulkan-Docs/blob/main/proposals/VK_KHR_ray_tracing_position_fetch.adoc#35-hlsl-mapping)
 - [x] HLSL DXC support: [SPIRV intrinsics only](https://github.com/KhronosGroup/Vulkan-Docs/blob/main/proposals/VK_KHR_ray_tracing_position_fetch.adoc#35-hlsl-mapping)

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.

**Comment by pdaniell-nv** [comment]
There is an NVIDIA beta driver with support for VK_KHR_ray_tracing_position_fetch available here: https://developer.nvidia.com/vulkan-driver

**Comment by jams3223** [comment]
> There is an NVIDIA beta driver with support for VK_KHR_ray_tracing_position_fetch available here: https://developer.nvidia.com/vulkan-driver

Does DX12 have the same extension?
