### ISSUE TITLE
Task list for VK_KHR_cooperative_matrix release

### ISSUE THREAD

**Issue by kpet** [KhronosGroup/Vulkan-Docs#2161]
This extension adds support for using cooperative matrix types in SPIR-V. Cooperative matrix types
are medium-sized matrices that are primarily supported in compute shaders, where the storage for
the matrix is spread across all invocations in some scope (usually a subgroup) and those
invocations cooperate to efficiently perform matrix multiplies.

The task list for the VK_KHR_cooperative_matrix release is:

 - [ ] Vulkan Specification:  
 - [ ] SPIRV specification:  
 - [ ] SPIRV Headers:  
 - [ ] SPIRV tools released: 
 - [ ] GLSL extension: 
 - [ ] Glslang implementation: 
 - [ ] Conformance tests released: 
 - [ ] SDK released: 

     - [ ] Validation layer: 
     - [ ] Emulation layer: 

 - [ ] Vulkan Guide:  
 - [ ] API Examples:  
 - [ ] Shaderc:  
 - [ ] HLSL mapping:
 - [ ] HLSL glslang support:
 - [ ] HLSL DXC support: 

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.

**Comment by archimedus** [comment]
I started Validation Layers in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/6093

**Comment by nihui** [comment]
GLSL extension:  https://github.com/KhronosGroup/GLSL/pull/208

**Comment by nihui** [comment]
https://github.com/nihui/vkpeak/releases/tag/20230805

hi, I added the fp16-matrix test project based on VK_KHR_cooperative_matrix for vkpeak

fp16-matrix value added for all VK_KHR_cooperative_matrix capable devices, such as rtx20+ and rdna3
It reflects the computing power of tensorcore or similar AI engine on the device
