### ISSUE TITLE
Task list for VK_EXT_host_image_copy release

### ISSUE THREAD

**Issue by ShabbyX** [KhronosGroup/Vulkan-Docs#2177]
This extension allows copies to and from images to be done on the host, improving the performance and memory usage in certain scenarios.

The task list for the VK_EXT_host_image_copy release is:

 - [x] Vulkan Specification: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_EXT_host_image_copy.html
 - [x] Conformance tests released: https://github.com/KhronosGroup/VK-GL-CTS/releases/tag/vulkan-cts-1.3.7.0
 - [x] SDK released: [SDK 1.3.261.1 (August 2023)](https://vulkan.lunarg.com/sdk/home)
     - [x] Validation layer: https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/6290

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.

**Comment by krOoze** [comment]
I feel "layout swizzling" is poorly specified. What exactly is it?

**Comment by krOoze** [comment]
It is not immediately clear to me why the extension requires `VK_KHR_copy_commands2`. At the first sight it does not seem to extend any of its functionality, and meanwhile rolls out its own new functions.

**Comment by ShabbyX** [comment]
Thanks for the feedback. There's a blog post coming that clarifies some/most of these, let me know which of these still need a response after that.

Regarding "physical layout/swizzling", it's referring to the layout of the pixels in device memory which is not "linear". Here's an example of such a layout a GPU may choose: https://en.wikipedia.org/wiki/Z-order_curve

And to be completely clear, all the functionality _is_ performed on the host. You can tell by the fact that the entry points do not start with `vkCmd` or take a command buffer.

**Comment by krOoze** [comment]
That sounds pretty close to what VkImageTiling` is supposed to cover. Should instead stick to that nomenclature?

**Comment by ShabbyX** [comment]
> That sounds pretty close to what VkImageTiling is supposed to cover. Should instead stick to that nomenclature?

It does. The spec itself never calls it swizzling though. It's the non-normative text that uses it because it's familiar to graphics devs (and is the concrete meaning of the OPTIMAL tiling)

> So doesn't glDraw start with cmd

Which is not a Vulkan command.

> I mean vkQueueSubmit does not begin with cmd, yet introduces work on the GPU.

And that command also runs on the host, even if it's scheduling GPU work (which, you can tell by it taking VkCommandBuffers). In Vulkan, if something interacts with the GPU, it generally needs a VkCommandBuffer. If there are exceptions (though I don't have any off the top of my head), that could be considered a design flaw. But the functions in VK_EXT_host_image_copy are not it; they don't take a command buffer and that clearly means they don't use the GPU.

**Comment by krOoze** [comment]
"swizzling" is invoked in `VK_HOST_IMAGE_COPY_MEMCPY_EXT` and `optimalTilingLayoutUUID` definition, which is normative text.

I still think it is too "cute" and implicit to assume host execution. Not to even mention trivial errors of accidentally swapping the two functions bacause of too similar names...
Besides, I think your assumptions are incorrect. Things without `cmd` may or may not do some things to the GPU (e.g. allocate device memory, write image views or descriptors, or whatnot. Meanwhile quite contrary, all `cmd` functions are likely on the host (with the whole point being permitting threading of command buffer creation on the CPU).

**Comment by ShabbyX** [comment]
Hi KrOoze! Now that https://www.khronos.org/blog/copying-images-on-the-host-in-vulkan is live, please let me know which of the above questions still stand.
