### ISSUE TITLE
Task list for VK_KHR_calibrated_timestamps release

### ISSUE THREAD

**Issue by aqnuep** [KhronosGroup/Vulkan-Docs#2281]
The task list for the  release is:

 - [x] Vulkan Specification: https://github.com/KhronosGroup/Vulkan-Docs/releases/tag/v1.3.273
 - [x] Conformance tests released: https://github.com/KhronosGroup/VK-GL-CTS/releases/tag/vulkan-cts-1.3.8.0
 - [x] SDK released: [Vulkan SDK 1.3.275.0](https://vulkan.lunarg.com/sdk/home)
 - [X] Validation layer: https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7119
     
As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.
