### ISSUE TITLE
Task list for VK_KHR_vertex_attribute_divisor release

### ISSUE THREAD

**Issue by ShabbyX** [KhronosGroup/Vulkan-Docs#2283]
This extension is a promotion of the VK_EXT_vertex_attribute_divisor extension, with an added property (supportsNonZeroFirstInstance) to indicate support for non-zero `firstInstance` in draw calls when the divisor is not 1. This allows the extension to be supported on hardware that traditionally supported OpenGL ES but not OpenGL.

The task list for the VK_KHR_vertex_attribute_divisor release is:

 - [x] Vulkan Specification: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_KHR_vertex_attribute_divisor.html
 - [x] Conformance tests released: https://github.com/KhronosGroup/VK-GL-CTS/releases/tag/vulkan-cts-1.3.8.0
 - [x] SDK released: [SDK 1.3.275.0 (January 2024)](https://vulkan.lunarg.com/sdk/home)
     - [x] Validation layer: https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7152

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.

**Comment by ziga-lunarg** [comment]
Validation layers support: https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7152
