### ISSUE TITLE
Task list for VK_KHR_video_encode_queue, VK_KHR_video_encode_h264, VK_KHR_video_encode_h265, and VK_KHR_video_maintenance1

### ISSUE THREAD

**Issue by aqnuep** [KhronosGroup/Vulkan-Docs#2284]
These extensions add support for the following Vulkan Video features:

- VK_KHR_video_encode_queue - general video encode support
- VK_KHR_video_encode_h264 - H.264/AVC video encode support
- VK_KHR_video_encode_h265 - H.265/HEVC video encode support
- VK_KHR_video_maintenance1 - miscellaneous improvements to video decoding and encoding

The task list for the VK_KHR_video_encode_queue, VK_KHR_video_encode_h264, VK_KHR_video_encode_h265, and VK_KHR_video_maintenance1 release is:

 - [x] Vulkan Specification:
     - [VK_KHR_video_encode_queue](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_KHR_video_encode_queue.html)
     - [VK_KHR_video_encode_h264](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_KHR_video_encode_h264.html)
     - [VK_KHR_video_encode_h265](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_KHR_video_encode_h265.html)
     - [VK_KHR_video_maintenance1](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_KHR_video_maintenance1.html)
 - [x] Vulkan Proposal Documents:
     - [VK_KHR_video_encode_queue](https://github.com/KhronosGroup/Vulkan-Docs/blob/main/proposals/VK_KHR_video_encode_queue.adoc)
     - [VK_KHR_video_encode_h264](https://github.com/KhronosGroup/Vulkan-Docs/blob/main/proposals/VK_KHR_video_encode_h264.adoc)
     - [VK_KHR_video_encode_h265](https://github.com/KhronosGroup/Vulkan-Docs/blob/main/proposals/VK_KHR_video_encode_h265.adoc)
     - [VK_KHR_video_maintenance1](https://github.com/KhronosGroup/Vulkan-Docs/blob/main/proposals/VK_KHR_video_maintenance1.adoc)
 - [x] Conformance tests released: Vulkan CTS 1.3.8.1
 - [x] SDK released: [Vulkan SDK 1.3.275.0](https://vulkan.lunarg.com/sdk/home)
     - [x] Validation layer: https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7177
 - [x] [Blog Post](https://www.khronos.org/blog/khronos-finalizes-vulkan-video-extensions-for-accelerated-h.264-and-h.265-encode)
 - [x] Drivers:
     - NVIDIA Beta driver: [Windows and Linux](https://developer.nvidia.com/vulkan-driver)
     - Intel driver: coming soon
     - AMD driver: coming soon

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.
