### ISSUE TITLE
Task list for VK_KHR_video_decode_av1

### ISSUE THREAD

**Issue by aqnuep** [KhronosGroup/Vulkan-Docs#2300]
This extension adds support for AV1 video decode.

The task list for the VK_KHR_video_decode_av1 release is:

 - [x] Vulkan Specification: [VK_KHR_video_decode_av1](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_KHR_video_decode_av1.html)
 - [x] Vulkan Proposal Document: [VK_KHR_video_decode_av1](https://github.com/KhronosGroup/Vulkan-Docs/blob/main/proposals/VK_KHR_video_decode_av1.adoc)
 - [x] Conformance tests released: Vulkan CTS 1.3.8.1
 - [x] SDK released: [Vulkan SDK 1.3.280.0](https://vulkan.lunarg.com/sdk/home)
     - [x] Validation layer: https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7438
 - [x] [Blog Post](https://www.khronos.org/blog/khronos-releases-vulkan-video-av1-decode-extension-vulkan-sdk-now-supports-h.264-h.265-encode)
 - [x] Drivers:
     - NVIDIA driver: https://developer.nvidia.com/vulkan-driver
     - Intel driver: coming soon
     - AMD driver: https://www.amd.com/en/support/kb/release-notes/rn-rad-win-vulkan

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.
