### ISSUE TITLE
Task list for VK_KHR_load_store_op_none

### ISSUE THREAD

**Issue by ShabbyX** [KhronosGroup/Vulkan-Docs#2305]
This extension is an as-is promotion of VK_EXT_load_store_op_none. See the task list for that extension (https://github.com/KhronosGroup/Vulkan-Docs/issues/1620) for description.

The task list for the VK_KHR_load_store_op_none release is:

 - [x] Vulkan Specification:  https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_KHR_load_store_op_none.html
 - [x] Conformance tests released: https://github.com/KhronosGroup/VK-GL-CTS/releases/tag/vulkan-cts-1.3.8.0
 - [x] SDK released: [SDK 1.3.280.0 (March 2024)](https://vulkan.lunarg.com/sdk/home)
     - [x] Validation layer: https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7412

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.
