### ISSUE TITLE
Task list for VK_KHR_pipeline_binary release

### ISSUE THREAD

**Issue by stu-s** [KhronosGroup/Vulkan-Docs#2421]
- [x] Vulkan Specification:  https://github.com/KhronosGroup/Vulkan-Docs/releases/tag/v1.3.294, https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_KHR_pipeline_binary.html
 - [x] Conformance tests released: 
 - [ ] SDK released: 

     - [x] Validation layer: https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8450

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.

**Comment by pdaniell-nv** [comment]
The latest NVIDIA Vulkan beta driver (553.00 Windows and 550.40.70 Linux) supports this extension: https://developer.nvidia.com/vulkan-driver
