### ISSUE TITLE
Task list for VK_KHR_video_encode_quantization_map release

### ISSUE THREAD

**Issue by aqnuep** [KhronosGroup/Vulkan-Docs#2466]
This extension adds support for video encode quantization maps (quantization delta and emphasis maps).

The task list for the VK_KHR_video_encode_quantization_map release is:

 - [x] Vulkan Specification: [VK_KHR_video_encode_quantization_map](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_KHR_video_encode_quantization_map.html)
 - [x] Vulkan Proposal Document: [VK_KHR_video_encode_quantization_map](https://github.com/KhronosGroup/Vulkan-Docs/blob/main/proposals/VK_KHR_video_encode_quantization_map.adoc)
 - [x] Conformance tests released: [Vulkan CTS 1.4.1.1](https://github.com/KhronosGroup/VK-GL-CTS/releases/tag/vulkan-cts-1.4.1.1)
 - [x] SDK released: [Vulkan SDK 1.4.304](https://vulkan.lunarg.com/sdk/home)
     - [x] Validation layer: https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8911
 - [x] [Blog Post](https://www.khronos.org/blog/khronos-announces-vulkan-video-encode-av1-encode-quantization-map-extensions)
 - [x] Drivers:
     - NVIDIA driver: https://developer.nvidia.com/vulkan-driver
     - Intel driver: coming soon
     - AMD driver: https://www.amd.com/en/support/kb/release-notes/rn-rad-win-vulkan

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.
