### ISSUE TITLE
Task list for Vulkan 1.4 release

### ISSUE THREAD

**Issue by marty-johnson59** [KhronosGroup/Vulkan-Docs#2471]
Release Task List for Vulkan 1.4

Vulkan 1.4 is a milestone release that directly brings long-requested features and proven extensions into the core standard. By mandating these capabilities, we are enhancing Vulkan’s flexibility and performance across a wider range of devices, making it easier for developers to create cutting-edge applications with confidence that they will run reliably on any platform. 

Vulkan is an ecosystem-driven API; the Vulkan Working Group defines the specification, but the tools developers need to use the API come from many teams across the Vulkan community. This issue tracks the state of the various documents and software artifacts needed to develop Vulkan 1.4 applications. As each item is made public, the task will be checked off below. When all tasks have been checked off, this issue will be closed and the Vulkan 1.4 release will be complete.

The task list for the Vulkan 1.4 release is:

 - [x] Vulkan Specification:  https://docs.vulkan.org/spec/latest/index.html
 - [x] Vulkan Headers:  https://github.com/KhronosGroup/Vulkan-Headers
 - [x] SPIRV-Tools (https://github.com/KhronosGroup/SPIRV-Tools/)
 - [x] glslang support: https://github.com/KhronosGroup/glslang
 - [x] shaderc support (https://github.com/google/shaderc/)
 - [x] Vulkan 1.4 Conformance test Suite: https://github.com/KhronosGroup/VK-GL-CTS/releases/tag/vulkan-cts-1.4.1.0
 - [ ] Vulkan 1.4 SDK: 
 - [x] Validation layer: https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8955
 - [x] Loader support: https://github.com/KhronosGroup/Vulkan-Loader

**Comment by pdaniell-nv** [comment]
Vulkan 1.4 beta drivers for NVIDIA GPUs on Windows and Linux can be found here: https://developer.nvidia.com/vulkan-driver

**Comment by NogginBops** [comment]
Not sure if this is the issue for this, but it seems like 1.4 is missing it's own folder here:
https://registry.khronos.org/vulkan/specs/

**Comment by NogginBops** [comment]
Ok! I'd missed that communication.
Good to know.

**Comment by marty-johnson59** [comment]
All items complete - closing
