### ISSUE TITLE
Task list for VK_KHR_get_display_properties2 release

### ISSUE THREAD

**Issue by pdaniell-nv** [KhronosGroup/Vulkan-Docs#720]
The Khronos board of promoters have recently ratified a new Vulkan extension called `VK_KHR_get_display_properties2`. This adds new structures and functions to allow `VK_KHR_display` to be extended.

The task list for the `VK_KHR_get_display_properties2` extension release is:
- [ ] Headers, specs, etc. in https://github.com/KhronosGroup/Vulkan-Docs
- [ ] Vulkan specification in the [Vulkan Registry](https://www.khronos.org/registry/vulkan/)
- [x] Vulkan Conformance Test Suite in https://github.com/KhronosGroup/VK-GL-CTS
    - Done 2018-04-09: https://github.com/KhronosGroup/VK-GL-CTS/releases/tag/vulkan-cts-1.1.1.0
- [ ] Validation in https://github.com/KhronosGroup/Vulkan-ValidationLayers
- [ ] Vulkan Loader in https://github.com/KhronosGroup/Vulkan-Loader
- [ ] Vulkan SDK at https://vulkan.lunarg.com/

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.

This public issue task list release process for `VK_KHR_get_display_properties2` follows the same pattern we are experimenting with for [VK_KHR_draw_indirect_count](https://github.com/KhronosGroup/Vulkan-Docs/issues/719). If you have comments about the release process in general, please make them there. If you have comments specific to `VK_KHR_get_display_properties2`, please add them below.

**Comment by oddhack** [comment]
The extension spec is included in the 1.1.76 spec update.

**Comment by pdaniell-nv** [comment]
Loaded support was added here: https://github.com/KhronosGroup/Vulkan-Loader/pull/29

**Comment by mikes-lunarg** [comment]
Validation support was added here: https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/196
