### ISSUE TITLE
Task list for VK_KHR_8bit_storage release

### ISSUE THREAD

**Issue by pdaniell-nv** [KhronosGroup/Vulkan-Docs#737]
The Khronos board of promoters have recently ratified a new Vulkan extension called `VK_KHR_8bit_storage`. This is similar to [VK_KHR_16bit_storage](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VK_KHR_16bit_storage), but for 8-bit types.

The task list for the `VK_KHR_8bit_storage` extension release is:
- [x] Headers, specs, etc. in https://github.com/KhronosGroup/Vulkan-Docs
- [x] Vulkan specification in the [Vulkan Registry](https://www.khronos.org/registry/vulkan/)
- [x] Vulkan Conformance Test Suite in https://github.com/KhronosGroup/VK-GL-CTS
- [x] Validation in https://github.com/KhronosGroup/Vulkan-ValidationLayers
- [x] GLSL spec in https://github.com/KhronosGroup/GLSL
- [x] glslang support in https://github.com/KhronosGroup/glslang
- [x] SPIR-V headers in https://github.com/KhronosGroup/SPIRV-Headers
- [x] SPIR-V extension in https://github.com/KhronosGroup/SPIRV-Registry
- [x] SPIR-V tools in https://github.com/KhronosGroup/SPIRV-Tools
- [x] Vulkan SDK at https://vulkan.lunarg.com/

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.

This release task list follows the pattern we previously did for [VK_KHR_draw_indirect_count](https://github.com/KhronosGroup/Vulkan-Docs/issues/719) and [VK_KHR_get_display_properties2](https://github.com/KhronosGroup/Vulkan-Docs/issues/720).

If you have any questions or feedback, please leave comments below.

**Comment by johnkslang** [comment]
This will also include additional 16-bit progress:

- the GLSL extension is combined 8-bit and 16-bit
- the GLSL implementation in glslang implements both 8-bit and 16-bit
- updates to SPV_KHR_16bit_storage extension specification based on the recent work in the previous two bullets

**Comment by johnkslang** [comment]
Have published:

- SPIR-V headers that add SPV_KHR_8bit_storage
- SPIR-V extensions that add SPV_KHR_8bit_storage and update SPV_KHR_16bit_storage
- a pending PR for glslang: https://github.com/KhronosGroup/glslang/pull/1431
- GLSL GL_EXT_shader_16bit_storage extension, which includes both 8-bit and 16-bit

**Comment by dneto0** [comment]
SPIRV-Tools support is in https://github.com/KhronosGroup/SPIRV-Tools/pull/1662

**Comment by dneto0** [comment]
SPIRV-Tools support has landed. 
Remaining validation work captured by https://github.com/KhronosGroup/SPIRV-Tools/issues/1595 (but is the same incomplete status for SPV_KHR_16bit_storage)

**Comment by dneto0** [comment]
Currently SPIRV-Tools master has validation bugs that are causing valid shaders to be rejected.

To support the Vulkan CTS release, I have published tag https://github.com/KhronosGroup/SPIRV-Tools/tree/gitlab-spv-khr-8bit-storage which has the 8bit-storage as actually used to develop Vulkan CTS for the feature; that support is branched off an older commit on GitHub master.

**Comment by alegal-arm** [comment]
CTS: https://github.com/KhronosGroup/VK-GL-CTS/releases/tag/vulkan-cts-1.1.1.2

**Comment by oddhack** [comment]
Specs are published in the 1.1.80 update.

**Comment by pdaniell-nv** [comment]
Compiler and validation support for VK_KHR_8bit_storage is included in the newly released VulkanSDK-1.1.82. This feature is now fully released. Closing.
