### ISSUE TITLE
Task list for VK_KHR_vulkan_memory_model release 

### ISSUE THREAD

**Issue by jeffbolznv** [KhronosGroup/Vulkan-Docs#787]
The Khronos board of promoters recently ratified a new Vulkan extension called VK_KHR_vulkan_memory_model. This extension introduces a formal memory consistency model that documents the interactions between memory operations performed by multiple invocations/threads.

This extension is released *provisionally*, in order to get feedback from the community and to accommodate possible changes before it is finalized.

The task list for the VK_KHR_vulkan_memory_model extension release is:

* [x] Vulkan specification (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VK_KHR_vulkan_memory_model)
* [x] SPIRV-Registry (http://htmlpreview.github.io/?https://github.com/KhronosGroup/SPIRV-Registry/blob/master/extensions/KHR/SPV_KHR_vulkan_memory_model.html)
* [x] SPIRV-Headers (https://github.com/KhronosGroup/SPIRV-Headers/commit/dcf23bdabacc3c54b83b1f9367e7a8adb27f8d87)
* [x] SPIRV-Tools (https://github.com/KhronosGroup/SPIRV-Tools/commit/571251c8f807e199dbf18f109f7fdcf178c040a9)
* [x] GLSL extension (https://github.com/KhronosGroup/GLSL/blob/master/extensions/khr/GL_KHR_memory_scope_semantics.txt)
* [x] glslang implementation (https://github.com/KhronosGroup/glslang/commit/ddfb4a8022767b93658c17bd26a01f6d6859eac9)
* [x] Alloy model (https://github.com/KhronosGroup/Vulkan-MemoryModel)
* [x] Conformance tests (available at https://github.com/KhronosGroup/VK-GL-CTS/pull/123, not merged)

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.

**Comment by johnkslang** [comment]
https://github.com/KhronosGroup/GLSL/pull/23 is merged now (I don't have permission to check the box).

**Comment by jeffbolznv** [comment]
NVIDIA supports this extension in the new driver posted at https://developer.nvidia.com/vulkan-driver.

**Comment by jeffbolznv** [comment]
There is a short blog post about this extension release at https://www.khronos.org/blog/vulkan-has-just-become-the-worlds-first-graphics-api-with-a-formal-memory-model.-so-what-is-a-memory-model-and-why-should-i-care.

(Unrelated to that) Given that the CTS tests are available and they aren't being merged right away, I'm going to go ahead and mark it as complete and close this issue.

**Comment by jeffbolznv** [comment]
The CTS tests were merged/published in the latest release, see https://github.com/KhronosGroup/VK-GL-CTS/commit/af79dae406ff8f0649402d2e2d99baba6a35c0a1.
