### ISSUE TITLE
Task list for VK_KHR_shader_atomic_int64 release

### ISSUE THREAD

**Issue by drakos-amd** [KhronosGroup/Vulkan-Docs#796]
The Khronos board of promoters have recently ratified a new Vulkan extension called `VK_KHR_shader_atomic_int64`. This extension enables shaders to perform 64-bit atomic operations on signed and unsigned integers in storage buffers and shared variables. The supported operations include OpAtomicMin, OpAtomicMax, OpAtomicAnd, OpAtomicOr, OpAtomicXor, OpAtomicAdd, OpAtomicExchange, and OpAtomicCompareExchange.

The task list for the `VK_KHR_shader_atomic_int64` extension release is:
- [x] Headers, specs, etc. in https://github.com/KhronosGroup/Vulkan-Docs
- [x] Vulkan specification in the [Vulkan Registry](https://www.khronos.org/registry/vulkan/)
- [x] Vulkan Conformance Test Suite in https://github.com/KhronosGroup/VK-GL-CTS
- [x] Validation in https://github.com/KhronosGroup/Vulkan-ValidationLayers
- [x] GLSL spec in https://github.com/KhronosGroup/GLSL
- [x] glslang support in https://github.com/KhronosGroup/glslang
- [x] SPIR-V tools in https://github.com/KhronosGroup/SPIRV-Tools
- [x] Vulkan SDK at https://vulkan.lunarg.com/

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.

If you have any questions or feedback, please leave comments below.

**Comment by antiagainst** [comment]
There is no SPIR-V instruction named as `OpAtomicCompSwap`. I assume you mean `OpAtomicCompareExchange`?

**Comment by johnkslang** [comment]
Glslang is merged.

**Comment by antiagainst** [comment]
SPIRV-Tools (https://github.com/KhronosGroup/SPIRV-Tools/pull/1889) is also done.

**Comment by drakos-amd** [comment]
> There is no SPIR-V instruction named as OpAtomicCompSwap. I assume you mean OpAtomicCompareExchange?

Indeed, that's a typo.

**Comment by alegal-arm** [comment]
CTS coverage released in https://github.com/KhronosGroup/VK-GL-CTS/releases/tag/vulkan-cts-1.1.2.1
