### ISSUE TITLE
Task list for VK_EXT_scalar_block_layout

### ISSUE THREAD

**Issue by Tobski** [KhronosGroup/Vulkan-Docs#854]
A group of vendors have recently created a new extension `VK_EXT_scalar_block_layout`. This extension enables C-like structure layout for uniform and storage buffers, allowing non-scalar types to be aligned solely based on the size of their components. This issue will track the release of various components as they are made available.

The task list for the `VK_EXT_scalar_block_layout` extension release is:
- [x] Headers, specs, etc. in https://github.com/KhronosGroup/Vulkan-Docs
- [x] Vulkan specification in the [Vulkan Registry](https://www.khronos.org/registry/vulkan/)
- [x] Support for the new layout rules in [spirv-tools](https://github.com/KhronosGroup/SPIRV-Tools)
 - https://github.com/KhronosGroup/SPIRV-Tools/pull/2074
- [x] GLSL extension in the [GLSL repository](https://github.com/KhronosGroup/GLSL)
 - https://github.com/KhronosGroup/GLSL/pull/40
- [x] Support for the GLSL extension in [glslang](https://github.com/KhronosGroup/glslang)
 - https://github.com/KhronosGroup/glslang/pull/1586
- [x] Support in HLSL via [DXC](https://github.com/Microsoft/DirectXShaderCompiler)
 - https://github.com/Microsoft/DirectXShaderCompiler/pull/1716/files
- [x] Vulkan [Conformance Test Suite](https://github.com/KhronosGroup/VK-GL-CTS) ([Vulkan CTS 1.1.2.3](https://github.com/KhronosGroup/VK-GL-CTS/releases/tag/vulkan-cts-1.1.2.3))
- [x] Support in the [Validation Layers](https://github.com/KhronosGroup/Vulkan-ValidationLayers)
 - https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/497
- [x] Vulkan SDK at https://vulkan.lunarg.com/

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.

If you have any questions or feedback, please leave comments below.

**Comment by oddhack** [comment]
Specs / headers published in the v1.1.93 spec update.

**Comment by Tobski** [comment]
All components have now completed and been released :)
