### ISSUE TITLE
Task list for VK_KHR_shader_float16_int8 release

### ISSUE THREAD

**Issue by TomOlson** [KhronosGroup/Vulkan-Docs#872]
The Vulkan Working Group has defined a new extension `VK_KHR_shader_float16_int8`. This extension allows implementations to expose support for the SPIR-V Float16 and Int8 capabilities in Vulkan shaders. 
It also specifies precision requirements for half-precision floating-point SPIR-V operations. It is intended to be used with (but does not require) the VK_KHR_8bit_storage or VK_KHR_16bit_storage extensions, which allow use of these types inshader input and output interfaces. It interacts with VK_KHR_shader_float_controls, which allows applications to query and override certain aspects of the implementation's default floating point behavior. This issue will track the release of various components as they are made available.

The task list for the `VK_KHR_shader_float16_int8` extension release is:
- [x] Headers, specs, etc. in https://github.com/KhronosGroup/Vulkan-Docs (version 1.1.95)
- [x] Vulkan specification in the [Vulkan Registry](https://www.khronos.org/registry/vulkan/) (version 1.1.95)
- [x] GLSL extension in the [GLSL repository](https://github.com/KhronosGroup/GLSL) (https://github.com/KhronosGroup/GLSL/pull/44)
- [x] Support for the GLSL extension in [glslang](https://github.com/KhronosGroup/glslang) (https://github.com/KhronosGroup/glslang/pull/1613)
- [x] Vulkan [Conformance Test Suite](https://github.com/KhronosGroup/VK-GL-CTS) ([Vulkan CTS 1.1.2.3](https://github.com/KhronosGroup/VK-GL-CTS/releases/tag/vulkan-cts-1.1.2.3))
- [x] Support in the [Validation Layers](https://github.com/KhronosGroup/Vulkan-ValidationLayers) (https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/514 KhronosGroup/SPIRV-Tools#2153, https://github.com/KhronosGroup/SPIRV-Tools/pull/2188)
- [x] Vulkan SDK at https://vulkan.lunarg.com/ (1.1.96)

As each component is made public, the task will be checked off and PR / version references filled in above. When all tasks have been completed this issue will be closed and the extension will be fully released.

If you have any questions or feedback, please leave comments below.

**Comment by JoseEmilio-ARM** [comment]
@TomOlson we closed https://github.com/KhronosGroup/SPIRV-Tools/pull/2188 as we think we have now good coverage for the extension and therefore the "Support in the Validation Layers" task may be checked out.

**Comment by mikew-lunarg** [comment]
Closing out this old task list.  The SDK containing commits https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/514 was 1.1.96 2018-12-18
