### ISSUE TITLE
Task list for VK_KHR_shader_float_controls release

### ISSUE THREAD

**Issue by TomOlson** [KhronosGroup/Vulkan-Docs#873]
The Vulkan Working Group has defined a new extension `VK_KHR_shader_float_controls`, which allows applications to query and override the implementation's default floating point behavior for rounding modes, denormals, signed zero and infinity. This issue will track the release of various components as they are made available.

The task list for the `VK_KHR_shader_float_controls` extension release is:
- [x] Headers, specs, etc. in https://github.com/KhronosGroup/Vulkan-Docs (version 1.1.95)
- [x] Vulkan specification in the [Vulkan Registry](https://www.khronos.org/registry/vulkan/) (version 1.1.95)
- [x] Vulkan [Conformance Test Suite](https://github.com/KhronosGroup/VK-GL-CTS) ([Vulkan CTS 1.1.2.3](https://github.com/KhronosGroup/VK-GL-CTS/releases/tag/vulkan-cts-1.1.2.3))
- [x] Support in the [Validation Layers](https://github.com/KhronosGroup/Vulkan-ValidationLayers) (https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/513, https://github.com/KhronosGroup/SPIRV-Tools/pull/2177)
- [x] Vulkan SDK at https://vulkan.lunarg.com/ (version 1.1.121)

As each component is made public, the task will be checked off and PR / version references filled in above. When all tasks have been completed this issue will be closed and the extension will be fully released.

If you have any questions or feedback, please leave comments below.

**Comment by TomOlson** [comment]
Validation support has been merged

**Comment by TomOlson** [comment]
Release was completed some time ago - forgot to update with current SDK status. Closing.
