### ISSUE TITLE
Task list for VK_EXT_buffer_device_address release

### ISSUE THREAD

**Issue by jeffbolznv** [KhronosGroup/Vulkan-Docs#890]
The Vulkan 1.1.97 spec release includes the [VK_EXT_buffer_device_address](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VK_EXT_buffer_device_address) extension. This extension allows the application to query a 64-bit buffer device address value for a buffer, which can be used to access the buffer memory via the PhysicalStorageBufferEXT storage class in the GL_EXT_buffer_reference GLSL extension and SPV_EXT_physical_storage_buffer SPIR-V extension. The GLSL extension allows declaring SSBO block types as "reference" types that can be dereferenced in the shader, and reference types can be stored in buffer memory, as local variables, etc.. In essence, this gives pointer-like functionality in the shader.

The task list for the VK_EXT_buffer_device_address extension release is:

* [x] Vulkan specification (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VK_EXT_buffer_device_address)
* [x] SPIRV-Registry (https://github.com/KhronosGroup/SPIRV-Registry/pull/18)
* [x] SPIRV-Headers (https://github.com/KhronosGroup/SPIRV-Headers/pull/88)
* [x] SPIRV-Tools (https://github.com/KhronosGroup/SPIRV-Tools/pull/2267)
* [x] GLSL extension (https://github.com/KhronosGroup/GLSL/pull/49)
* [x] glslang implementation (https://github.com/KhronosGroup/glslang/pull/1644)
* [x] validation layer (https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/568)
* [ ] Conformance tests (written, not yet published)

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.

I expect to push the glslang/spirv changes by Monday.

**Comment by pdaniell-nv** [comment]
NVIDIA has released support for this new extension in their latest Vulkan beta driver here 
https://developer.nvidia.com/vulkan-driver.

**Comment by johnkslang** [comment]
> SPIRV-Registry (KhronosGroup/SPIRV-Registry#18)

This was done last week, but I don't have edit permission on the list.

**Comment by jeffbolznv** [comment]
Thanks John. I'm going to close this out without waiting for CTS. The CTS tests have been written but have a relatively high latency to publish.
