### ISSUE TITLE
Task list for VK_KHR_depth_stencil_resolve release

### ISSUE THREAD

**Issue by TomOlson** [KhronosGroup/Vulkan-Docs#892]
The Khronos board of promoters have ratified a new Vulkan extension called `VK_KHR_depth_stencil_resolve`. This extension adds support for automatically resolving multisampled depth/stencil attachments in a subpass in a similar manner as for color attachments.

The task list for the release of `VK_KHR_depth_stencil_resolve` is:
- [x] Headers, specs, etc. in https://github.com/KhronosGroup/Vulkan-Docs (version 1.1.97)
- [x] Vulkan specification in the [Vulkan Registry](https://www.khronos.org/registry/vulkan/) (version 1.1.97)
- [x] Vulkan Conformance Test Suite coverage in https://github.com/KhronosGroup/VK-GL-CTS
- [x] Validation support in https://github.com/KhronosGroup/Vulkan-ValidationLayers (https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/582)
- [x] Vulkan SDK support at https://vulkan.lunarg.com/

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.

If you have any questions or feedback, please leave comments below.

**Comment by alegal-arm** [comment]
CTS: https://github.com/KhronosGroup/VK-GL-CTS/releases/tag/vulkan-cts-1.1.3.0

**Comment by TomOlson** [comment]
Release is complete - closing
