### ISSUE TITLE
Task list for VK_NV_cooperative_matrix release

### ISSUE THREAD

**Issue by jeffbolznv** [KhronosGroup/Vulkan-Docs#923]
The Vulkan 1.1.101 spec release includes the [VK_NV_cooperative_matrix](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VK_NV_cooperative_matrix) extension. This extension adds support for using cooperative matrix types in SPIR-V. Cooperative matrix types are medium-sized matrices that are primarily supported in compute shaders, where the storage for the matrix is spread across all invocations in some scope (usually a subgroup) and those invocations cooperate to efficiently perform matrix multiplies. These operations are accelerated by NVIDIA Tensor Cores on Turing GPUs.

The task list for the VK_NV_cooperative_matrix extension release is:

* [x] Vulkan specification (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VK_NV_cooperative_matrix)
* [x] SPIRV-Registry (https://github.com/KhronosGroup/SPIRV-Registry/pull/20)
* [x] SPIRV-Headers (https://github.com/KhronosGroup/SPIRV-Headers/pull/94)
* [x] SPIRV-Tools (https://github.com/KhronosGroup/SPIRV-Tools/pull/2404)
* [x] GLSL extension (https://github.com/KhronosGroup/GLSL/pull/55)
* [x] glslang implementation (https://github.com/KhronosGroup/glslang/pull/1701)
* [x] validation layer (https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/742)
* [ ] Conformance tests (written, not yet published)
* [x] Sample application/benchmark (https://github.com/jeffbolznv/vk_cooperative_matrix_perf)

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.

**Comment by pdaniell-nv** [comment]
Driver versions 419.09 (Windows) and 418.31.03 (Linux) implement this extension and can be found here: https://developer.nvidia.com/vulkan-driver.

**Comment by oscarbg** [comment]
@pdaniell-nv can't see this interesting extension (VK_NV_cooperative_matrix) exposed on Titan V (Volta) on 419.09.. 
https://vulkan.gpuinfo.org/compare.php?compare=compare&id%5B5264%5D=on&id%5B4960%5D=on
is that expected? it's because Volta Tensor cores aren't "rich enough" to support it?
thanks..

**Comment by jeffbolznv** [comment]
Right, this is only currently supported on Turing.

**Comment by minisparrow** [comment]
could the warpgroup mma(H100 WGMMA) using this extension?
