### ISSUE TITLE
Task List for VK_KHR_uniform_buffer_standard_layout release

### ISSUE THREAD

**Issue by TomOlson** [KhronosGroup/Vulkan-Docs#964]
The Vulkan Working Group has defined a new extension `VK_KHR_uniform_buffer_standard_layout`, which relaxes alignment restrictions to allow the use of layouts equivalent to OpenGL's std430 in uniform buffers. This issue will track the release of various components as they are made available.

The task list for the `VK_KHR_uniform_buffer_standard_layout` extension release is:
- [x] Headers, specs, etc. in https://github.com/KhronosGroup/Vulkan-Docs (version 1.1.108)
- [x] Vulkan specification in the [Vulkan Registry](https://www.khronos.org/registry/vulkan/) (version 1.1.108)
- [x] Vulkan [Conformance Test Suite](https://github.com/KhronosGroup/VK-GL-CTS) ([Vulkan CTS 1.1.4.1](https://github.com/KhronosGroup/VK-GL-CTS/releases/tag/vulkan-cts-1.1.4.1))
- [x] Support in the Validation Layers (KhronosGroup/Vulkan-ValidationLayers#921)
- [x] Vulkan SDK at https://vulkan.lunarg.com/ (_SDK version_)

As each component is made public, the task will be checked off and PR / version references filled in above. When all tasks have been completed this issue will be closed and the extension will be fully released.

If you have any questions or feedback, please leave comments below.

**Comment by oddhack** [comment]
The Hpp repo got a fix shortly after I pushed the docs update, so I was able to complete the header update, too.

**Comment by gnl21** [comment]
The validation layers PR is here: https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/921. It won't work until there's a tag for v.108 or later in that repo.

**Comment by gnl21** [comment]
Validation support is now merged, so that task can be checked off now.

**Comment by gnl21** [comment]
The latest SDK release (1.1.114) contains support for this, so I think this issue can be resolved, @TomOlson.

**Comment by TomOlson** [comment]
Yep - release is complete. Thanks!
