### ISSUE TITLE
Task list for VK_EXT_fragment_shader_interlock release

### ISSUE THREAD

**Issue by jeffbolznv** [KhronosGroup/Vulkan-Docs#975]
The Vulkan 1.1.110 spec release includes the [VK_EXT_fragment_shader_interlock](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/chap44.html#VK_EXT_fragment_shader_interlock) extension. This extension is analogous to GL_ARB_fragment_shader_interlock, and provides a critical section for fragment shaders to avoid overlapping pixels being processed at the same time, and certain guarantees about the ordering of fragment shader invocations of fragments of overlapping pixels.

The task list for the VK_EXT_fragment_shader_interlock extension release is:

* [x] Vulkan specification (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/chap44.html#VK_EXT_fragment_shader_interlock)
* [x] SPIRV-Registry (https://github.com/KhronosGroup/SPIRV-Registry/pull/31)
* [x] SPIRV-Headers (https://github.com/KhronosGroup/SPIRV-Headers/pull/114)
* [x] SPIRV-Tools (https://github.com/KhronosGroup/SPIRV-Tools/pull/2650)
* [x] GLSL extension (same as OpenGL - https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_fragment_shader_interlock.txt)
* [x] glslang implementation (https://github.com/KhronosGroup/glslang/pull/1786)
* [x] validation layer (https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/1023)
* [x] Conformance tests (https://github.com/KhronosGroup/VK-GL-CTS/releases/tag/vulkan-cts-1.1.5.1)

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released. I expect to push most of this tomorrow.

**Comment by Degerz** [comment]
An interesting observation to note is that it's not quite a clone of GL_ARB_fragment_shader_interlock since it adds an additional capability to interact with Nvidia's Turing architecture variable rate shading hardware implementation!

**Comment by jeffbolznv** [comment]
Those were originally added in https://github.com/KhronosGroup/GLSL/blob/master/extensions/nv/GLSL_NV_shading_rate_image.txt. The SPIR-V and Vulkan extensions include that (optional) support.

**Comment by pdaniell-nv** [comment]
An NVIDIA beta driver with support for this extension can be found here https://developer.nvidia.com/vulkan-driver
