### ISSUE TITLE
Task list for VK_EXT_texel_buffer_alignment release 

### ISSUE THREAD

**Issue by jeffbolznv** [KhronosGroup/Vulkan-Docs#989]
The Vulkan 1.1.113 spec release includes the [VK_EXT_texel_buffer_alignment](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/chap44.html#VK_EXT_texel_buffer_alignment) extension. This extension allows implementations to advertise either a byte alignment or single texel alignment for each of uniform texel buffers and storage texel buffers, independently.

The task list for the VK_EXT_texel_buffer_alignment extension release is:

* [x] Vulkan specification (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/chap44.html#VK_EXT_texel_buffer_alignment)
* [x] Validation layer (https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/1067)
* [x] Conformance tests  [vulkan-cts-1.1.6.0](https://github.com/KhronosGroup/VK-GL-CTS/releases/tag/vulkan-cts-1.1.6.0)

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.

**Comment by jeffbolznv** [comment]
Closing.
