### ISSUE TITLE
Task list for VK_EXT_shader_demote_to_helper_invocation release 

### ISSUE THREAD

**Issue by jeffbolznv** [KhronosGroup/Vulkan-Docs#990]
The Vulkan 1.1.113 spec release includes the [VK_EXT_shader_demote_to_helper_invocation](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/chap44.html#VK_EXT_shader_demote_to_helper_invocation) extension. This extension adds Vulkan support for the SPV_EXT_demote_to_helper_invocation SPIR-V extension. That SPIR-V extension provides a new instruction OpDemoteToHelperInvocationEXT allowing shaders to "demote" a fragment shader invocation to behave like a helper invocation for its duration. The demoted invocation will have no further side effects and will not output to the framebuffer, but remains active and can participate in computing derivatives and in subgroup operations. This is a better match for the "discard" instruction in HLSL.

The task list for the VK_EXT_shader_demote_to_helper_invocation extension release is:

* [x] Vulkan specification (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/chap44.html#VK_EXT_shader_demote_to_helper_invocation)
* [x] SPIRV-Registry (https://github.com/KhronosGroup/SPIRV-Registry/pull/43)
* [x] SPIRV-Headers (https://github.com/KhronosGroup/SPIRV-Headers/pull/121)
* [x] SPIRV-Tools (https://github.com/KhronosGroup/SPIRV-Tools/pull/2707)
* [x] GLSL extension (https://github.com/KhronosGroup/GLSL/pull/76)
* [x] glslang implementation (https://github.com/KhronosGroup/glslang/pull/1817)
* [x] validation layer (https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/1066)
* [x] Conformance tests (https://github.com/KhronosGroup/VK-GL-CTS/releases/tag/vulkan-cts-1.1.5.1)

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released. I expect to push most of this tomorrow.

**Comment by jeffbolznv** [comment]
(fixed copy/paste)

**Comment by jekstrand** [comment]
Everything has been checked off.  Can this be closed?

**Comment by jeffbolznv** [comment]
Closing
