### ISSUE TITLE
Task list for VK_KHR_imageless_framebuffer release

### ISSUE THREAD

**Issue by Tobski** [KhronosGroup/Vulkan-Docs#996]
The Vulkan 1.1.114 spec release includes the [VK_KHR_imageless_framebuffer](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/chap44.html#VK_KHR_imageless_framebuffer) extension. 

This extension allows framebuffers to be created without the need for creating images first, allowing more flexibility in how they are used, and avoiding the need for many of the confusing compatibility rules.

Framebuffers are now created with a small amount of additional metadata about the image views that will be used in VkFramebufferAttachmentsCreateInfoKHR, and the actual image views are provided at render pass begin time via VkRenderPassAttachmentBeginInfoKHR.

The task list for the VK_KHR_imageless_framebuffer extension release is:

* [x] Vulkan specification ([VK_KHR_imageless_framebuffer](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/chap44.html#VK_KHR_imageless_framebuffer))
* [x] Validation layer (MR pending: https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/1040)
* [x] Conformance tests ([Vulkan CTS 1.1.5.0](https://github.com/KhronosGroup/VK-GL-CTS/releases/tag/vulkan-cts-1.1.5.0))

As each component is made public, the task will be checked off. When all tasks have been completed this issue will be closed and the extension will be fully released.

**Comment by pdaniell-nv** [comment]
Driver support for NVIDIA GPUs can be found here: https://developer.nvidia.com/vulkan-driver

**Comment by Tobski** [comment]
This has now been fully released - validation support etc. will appear in the next (1.1.114) SDK release.
